### ISSUE TITLE
TBI - Enhance UITextField, UIComboBox label interaction behaviour

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#1003]
### Description (include screenshots)
We received feedback regarding behaviour of clicks on labels for inputs like UIComboBox, UITextInput.
Like:
![image](https://user-images.githubusercontent.com/90789422/236468824-c1ad2967-c24d-4667-a066-45d9fb145666.png)

1. Currently highlighted area opens dropdown menu or focuses input field. Expected behavior is that only click on text should apply focus and show dropdown menu;
2. When dropdown is opened and we click on label, then dropdown menu will be reopened. Expected behavior is to toggle visibility of dropdown menu, but focus should be placed in input;

### Value
Improves user experience regarding Dropdown/Combobox components

### Tasks
- [ ] Enhance UITextField - https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/components/UIInput/UITextInput.tsx
- [ ] Enhance UIComboBox - https://github.com/SAP/open-ux-tools/tree/main/packages/ui-components/src/components/UIComboBox
- [ ]  Enhance UIDropdown - https://github.com/SAP/open-ux-tools/tree/main/packages/ui-components/src/components/UIDropdown
- [ ] Enhance UITreeDropdown? - https://github.com/SAP/open-ux-tools/tree/main/packages/ui-components/src/components/UITreeDropdown

@gpeuc
