### ISSUE TITLE
TBI - Extend deploy-config custom task to handle archivePath parameter

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1017]
### Description (include screenshots)

Allow `archivePath`to be passed to ABAP custom task so that instead of generating the zip https://github.com/SAP/open-ux-tools/blob/main/packages/deploy-tooling/src/ui5/index.ts#L29 on the fly, its read from https://github.com/SAP/open-ux-tools/blob/main/packages/deploy-tooling/src/cli/archive.ts#L17 using `config.archivePath` which is a parameter passed in from the. calling client.

### Value
Provides additional control from a third party client when exeuting the custom UI5 task.

### Architecture Elaboration
Does it requires architecture elaboration? No

### Notes
The naming of the archive should default to `archive.zip` rather than appending the timestamp. 

### Tasks
- [ ] Update the `AbapDeployConfig` interface to accept `archivePath?: string;`
- [ ] If archivePath is specified, read it from the specified location
- [ ] Update test cases to reflect change

**Comment by longieirl** [comment]
Upon further review, this is not no a requirement and any task requiring archive-path support should be delegated out to the cli task.
