### ISSUE TITLE
TBI - ui-components, Enhancements for UIContextualMenu(used for context menues and dropdown butons) + Combobox&Dropdown inputs

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#1033]
### Value
Dropdown items for buttons or context menu already supports icons, but visualisation is not adjusted:
![image](https://github.com/SAP/open-ux-tools/assets/90789422/6c42f188-e091-44fa-b385-79b933cbcc45)

Expected visualisation is:
![image](https://github.com/SAP/open-ux-tools/assets/90789422/6dc0e8ed-977e-4d20-b63d-b22674958140)

### Tasks
- [x] Apply sizing to icons -> PR [#1034](https://github.com/SAP/open-ux-tools/pull/1034)
- [x] Show icons on right side of menu -> PR [#1034](https://github.com/SAP/open-ux-tools/pull/1034)

Additional:

- [x] Add an option of horizontal divider
- [x] Add possibility for non-selectable subtitle line item
- [x] Combobox and Dropdown inputs - support headers and separators

<img width="335" alt="Screenshot 2023-05-25 at 12 41 50" src="https://github.com/SAP/open-ux-tools/assets/44162846/e66c0950-171c-4cae-a045-80f27a8bd794">

@gpeuc

**Comment by gpeuc** [comment]
Fluent has this by default already, maybe we can just tweak the styling and that's it?

https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

<img width="468" alt="Screenshot 2023-08-09 at 14 25 11" src="https://github.com/SAP/open-ux-tools/assets/44162846/8d1821b9-2bfb-4a8b-ae71-40a6f7760d9b">
