### ISSUE TITLE
FEATURE - allow adding the new cds-plugin-ui5 to CAP 

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1041]
_As a **CAP & UI5 developer**,
I want to **make use of the new [cds-plugin-ui5](https://www.npmjs.com/package/cds-plugin-ui5)**,
so that I **can easily develop typescript UI5 applications in CAP**_

### Description
The purpose of this new functionality is to improve the developer experience for UI5 developers in a CAP project, especially the ones using typescript. The goal is to create a reusable module that can be integrated into generators that enables the `cds-plugin-ui5`, as well as, an enhancement to the `@sap-ux/create` module so that it can be used to enhancing existing projects with a simple CLI command.

### Technical Design
Create a new `cap-config-writer` with a two functions
* `checkCdsUi5PluginEnabled` - to check if the module and the required configurations are already available
* `enabledCdsUi5Plugin` - add the plugin and update the required versions
* evaluate if any user input as prompts could be added (right now, I don't know anything but maybe a confirm prompt)
Enhance

Enhance the `create` module with an `add cds-plugin-ui5` option

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a CAP project 
**when** I execute `npm init @sap-ux add cds-plugin-ui5`
**then** my existing project will be enhanced with all required configurations.

### Notes
All changes required are in the root `package.json` of a CAP project:

1. add `cds-ui5-plugin` to `devDependencies`
2. set `workspaces: [ './app/* ]`
3. Update the `@sap/cds` dependency to `^6.8.2` if it is lower
 
### Tasks
- [ ] Create new module allowing to add the `cds-plugin-ui5`
- [ ] Integrating the module into `@sap-ux/create`
- [ ] Unit Tests added
- [ ] Test Cases defined 

### FYI
@petermuessig @Klaus-Keller @vobu @danjoa

**Comment by IainSAP** [comment]
@tobiasqueck Do we also need to include an `npm`  version check  when implementing `checkCdsUi5PluginEnabled ` (npm ver, workspaces, cds-ui5-plugin, cds ver).

**Comment by tobiasqueck** [comment]
> Do we also need to include an npm version check when implementing checkCdsUi5PluginEnabled  (npm ver, workspaces, cds-ui5-plugin, cds ver).

I'd say no because the check is for the project itself whereas an npm version check would be a check of the local environment

> Should enabledCdsUi5Plugin also add ux-specification to each application package.json (not the root)

No, technically it is ok, to keep it in root, it will work, and I could image that some expert developers will keep one version in root and remove them from our generated project (Note: some, not the majority)

**Comment by devinea** [comment]
Also, npm v7 is min required for workspaces and our currently min supported Node v16 ships with npm v8. So I think we can skip this check entirely.

**Comment by Klaus-Keller** [comment]
>@Klaus-Keller @tobiasqueck Can we please update the checkCdsUi5PluginEnabledAPI to return which checks failed. For example, since you have already determined the CDS version, please return this if it fails. Otherwise consumers will need to again check and since enableCdsUi5plugin doesnt install the correct CDS version we will need to report the failed checks in some way.

@IainSAP, as the PR is closed, I'll reply here. We can export the individual checks, I've create draft PR: 
https://github.com/SAP/open-ux-tools/pull/1064

While doing it I realized, I would have a better feeling to export `hasMinCdsVersion()` only. Function `getWorkspaceInfo()` has bit more of an internal character and `hasCdsPluginUi5()` purely checks the `devDependendies` for `cds-plugin-ui5`, no dedicated version check, yet. Let me know what you think, if `hasMinCdsVersion()` is enough I'd just export that.

**Comment by docirl** [comment]
Hi Klaus,
For the generator flow we will need to check the cds version and also if the project does not have workspaces enabled. As discussed on the call yesterday, we would like access to the results of each of these checks if possible (cds version, workspaces enabled, plugin used), how we get them does not really matter. Having access to the checks individually or by enhancing the current method `checkCdsUi5PluginEnabled` to return the results, perhaps something like Iain suggested 
 by conditionally returning the check results if not true. But the main thing we need is more granular results on the checks.

Also, for the npm version check that we discussed I think this needs to be enhanced to use command `npm version` instead of using semver to check the CDS version. The version spec'd in the package.json can be broad ranges, with the version actually installed being something else. Example with current check:

**Comment by docirl** [comment]
Hi Klaus,

For the generator flow we will need to check the cds version and also if the project does not have workspaces enabled. As discussed on the call yesterday, we would like access to the results of each of these checks if possible (cds version, workspaces enabled, plugin used), how we get them to me does not really matter. Having access to the checks individually or by enhancing the current method `checkCdsUi5PluginEnabled` to return the results, perhaps something like Iain suggested by conditionally returning the check results if not true? But the main thing we need is more granular results on the checks.

Secondly, for the npm version check that we discussed I think this needs to be enhanced to use `npm version` instead of using `semver` to check the cds version. The version spec'd in the package.json can use broad ranges, with the version actually installed being anywhere in-between. Example with current check:

`"@sap/cds": ">=6.7.0",` (taken from [here](https://github.com/SAP-samples/cap-sflight)) will be coerced to 6.7 and will fail the min check. Running `npm i` on this will install the latest 6.8.2. The user could also have something less than 6.8.2 though.

We need to know the exact version that is installed to determine if we should show the question for enabling workspaces, and using semver has a bit of guess work to get the version but checking the version directly using `npm version` we would always get the exact version that is installed.

What are the thoughts on this?

**Comment by Klaus-Keller** [comment]
>For the generator flow we will need to check the cds version and also if the project does not have workspaces enabled. As discussed on the call yesterday, we would like access to the results of each of these checks if possible (cds version, workspaces enabled, plugin used), how we get them to me does not really matter. Having access to the checks individually or by enhancing the current method checkCdsUi5PluginEnabled to return the results, perhaps something like Iain suggested by conditionally returning the check results if not true? But the main thing we need is more granular results on the checks.

I understand the reason for checking `hasMinCdsVersion()` individually: the generator would not even provide the option for adding a TypeScript app to an existing CAP node.js project if a minimum version is not met. What are the reasons for checking workspaces and dev dependency to `cds-plugin-ui5` individually? Is it to inform the user or are there technical reasons for it? By the way, due to the usage of `mem-fs` we can comfortably simulate the exact changes, that would be applied to the project. To test this you can run the following terminal command in root of any CAP project:

```
$ npx @sap-ux/create@latest add cds-plugin-ui5  --simulate
```
As result it shows the file changes that would be applied:

![image](https://github.com/SAP/open-ux-tools/assets/66327622/e689f25a-333a-45de-8bb1-92cad2863824)

Would that be a good way to inform the user of the generator about the exact changes that will be applied to the project?


>Secondly, for the npm version check that we discussed I think this needs to be enhanced to use npm version instead of using semver to check the cds version. The version spec'd in the package.json can use broad ranges, with the version actually installed being anywhere in-between. Example with current check:

>"@sap/cds": ">=6.7.0", (taken from [here](https://github.com/SAP-samples/cap-sflight)) will be coerced to 6.7 and will fail the min check. Running npm i on this will install the latest 6.8.2. The user could also have something less than 6.8.2 though.

>We need to know the exact version that is installed to determine if we should show the question for enabling workspaces, and using semver has a bit of guess work to get the version but checking the version directly using npm version we would always get the exact version that is installed.

>What are the thoughts on this?

I don't think checking installed version of an individual project will help. Even if the project we are current looking at has a valid version installed, it doesn't ensure that other installation of the project use an older version, which is valid for the semver range, but not sufficient for adding `cds-plugin-ui5`. I also thought about checking the lock file, but this is also not a valid approach, because a lock file isn't necessarily present.
What matters is the entry in `package.json`, it can't contain a version or semver range that allows for versions lower than `6.8.2`, because then theoretically there could be project installations that have an older version we not support.

**Comment by docirl** [comment]
In the generator we want to check the version of cds and also if the project has workspaces already configured. If they have workspaces set up then we would not show the question if they want to enable this. So checking the cds version alone here would not be sufficient, as it could be possible they have workspaces enabled separately to our tooling(?). So we would like access to the results of each of these checks to so we can best configure the generator options based on their config.

Ok I think for now using semver is ok, to allow for further discussion here on how we read the version. I can try look at semver to see if we can handle ranges a bit better for the example I provided.

**Comment by Klaus-Keller** [comment]
> In the generator we want to check the version of cds and also if the project has workspaces already configured. If they have workspaces set up then we would not show the question if they want to enable this.

What if workspaces are enabled but the dev dependency to `cds-plugin-ui5` is not present? Or vice versa?  
Function `enableCdsUi5Plugin()` ensures 3 features:
- minimum version of `@sap/cds`
- workspaces are enabled for `app/` folder
- dev dependency to `cds-plugin-ui5` exists

The function is not designed to switch these features or prerequisites individually, intension was to ensure are features are present in a given CAP project. Splitting up the checks into 3 separate checks would indicate that the features can be switched on individually, which is not planed and should not be possible. From Fiori tools perspective we expect all 3 features are present.

**Comment by docirl** [comment]
Ok but the agreement for the generator flow is that we will check the @sap/cds version, if version is minimum required version and then the user does not have have workspaces configured then we will include a prompt to add this. Perhaps checking the plugin here too would make sense. I dont think the function requr

**Comment by Klaus-Keller** [comment]
Hi @docirl,

From our discussion last week, I understood the following generator flow:

```mermaid
graph TD
    start((Generate app in CAP))-->hasMinCdsVersion["hasMinCdsVersion()"]
    hasMinCdsVersion-- yes -->cdsUi5PluginEnabled["checkCdsUi5PluginEnabled()"]
    cdsUi5PluginEnabled-- yes -->newProjectSetup["New project setup, TypeScript in CAP possible"]
    cdsUi5PluginEnabled-- no -->askEnable["Should min @sap/cds version, workspaces, dev dependency cds-plugin-ui5 be enabled?"]
    askEnable-- yes -->newProjectSetup
    askEnable-- no -->oldProjectSetup
    hasMinCdsVersion-- no -->oldProjectSetup["Old project setup, no TypeScript apps"]
```

Is this correct?

**Comment by Klaus-Keller** [comment]
Ok: https://github.com/SAP/open-ux-tools/pull/1064

**Comment by Klaus-Keller** [comment]
Hi @tobiasqueck, I think this can be closed now.
