### ISSUE TITLE
FEATURE - Consolidate livereload middlewares

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1042]
_As a **UI5 developer**,
I want to **to have one middleware that I use for having a live reload on change**,
so that I **don't have decide whether to use `ui5-middleware-livereload` or `fiori-tools-appreload`**_

### Description
Due to historical reasons and slightly different requirements, the UI5 community developed https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/ui5-middleware-livereload and the Fiori tools team developed https://www.npmjs.com/package/@sap/ux-ui5-tooling#1-application-reload. Both middlewares do practically the same just with small differences in behavior.
The goal of this "feature request" is to merge both together in one middleware maintained by both the open UX tools team as well as the creator of the community middleware @vobu (and other interested community members).

### Technical Design
n/a

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ui5 project 
**when** I need a middleware for live reloading of sources
**then** I am not confused which one to use

### Tasks
- [ ] @vobu move the https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload into this repo at `./packages/ui5-middleware-liveload`
- [ ] @tobiasqueck add the required settings for sonar, teams, etc. and add @sap-ux scope
- [ ] add Unit Tests
- [ ] release initial version as 0.1
- [ ] convert coding to typescript and align with other `open-ux-tools` configs
- [ ] release a version 0.1.1
- [ ] @zdravko-georgiev enhance the middleware with missing features from `fiori-tools-appreload`
- [ ] Release another version 
- [ ] Not part of this repo: remove `fiori-tools-appreload` from `@sap/ux-ui5-tooling` and use this new middleware instead
- [ ] Not part of this repo: update community generators to use the new module

**Comment by marianfoo** [comment]
any progress here? 
would be great to have `exclusions` from `ui5-middleware-livereload`
