### ISSUE TITLE
FEATURE - Publish additional adaptation project functionality

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1329]
As a **developer**,
I want to **be able to access at the sources for adaptation projects tooling**,
so that I **can reuse it for my own tools or to just look at to better understand it**

### Description
With https://github.com/SAP/open-ux-tools/issues/1149 the `open-ux-tools` contain the core functionality for working with adaptation projects, however, some functionality is still in internal modules:
* add component usages
* add new model
* add local annotations
* change data source

With this task, the functionality will be published as well, so that it can be reused in different environments.

### Technical Design
Everything should fit into the `adp-tooling` module and should be based on `ejs`. The published functionality should then be integrated back into `@sap/generator-adaptation-project` as well as the `@sap-ux/create` module for the grow-as-you-go paradigm

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a browser
**when** I go to the `open-ux-tools` repository
**then** I will be able to find the adaptation project functionality.

**Given** I have a use `@sap-ux/create` or `@sap/generator-adaptation-project`
**when** I use it
**then** I have access to all published functionality

### Tasks
- [x] move functionality into `adp-tooling` module and expose separate `generate<feature>` functions
- [x] unit Tests added
- [x] integrate the functionality back into the existing `@sap` modules
- [ ] expose the functionality as with `@sap-ux/create
