### ISSUE TITLE
FEATURE - Deploy adaptation projects to ABAP

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1330]
_As an **adaptation project developer**,
I want to **do be able to add a deployment configuration to my adaptation project**,
so that I **can deploy it to an ABAP based backend**_

### Description
With https://github.com/SAP/open-ux-tools/issues/1149 the `open-ux-tools` now fully support working locally (in VSCode) on adaptation projects. As a next step, it is required to deploy a local adaptation project to an ABAP backend. To support this, two separate steps are required:
1. Enhancing the project with the required configuration for deployment
2. Enhancing the tools to do the actual deployment

#### Enhancing the project with the required configuration for deployment
The `@sap-ux/create` module already offers the functionality to generate an adaptation project by executing `sap-ux generate adaptation-project`. To support the grow-as-you-go paradigm, it should be enhanced with something like `sap-ux add deploy-config` allowing to add a deployment configuration to an existing project. The command should work for both classic application projects and adaptation projects. Ideally, both should use exactly the same configuration.
The functionality for generating a deployment configuration should be encapsulated in a new module `@sap-ux/deploy-config-writer` (similar to `@sap-ux/mockserver-config-writer). It should be checked wether `@sap-ux/system-access` could be used here.

#### Enhancing the tools to do the actual deployment
The `deploy-tooling` supports the full range of deployment options for UI5 applications covering both BAS and VSCode and different authentication options. So, a possible solution would be to enhance this for adaptation projects.
The only difference is the used backend service which is encapsulated already in https://github.com/SAP/open-ux-tools/tree/main/packages/axios-extension#layered-repository-service, so the required enhancements should be feasible.   

For backward compatibility, this functionality should then also be integrated back into `https://www.npmjs.com/package/@sap/adp-cli`

Note: it should be distinguished between an on-premise system and an ABAP Cloud system. In the on-prem case, the LREP service should be used for deployment, in an ABAP Cloud system, we should use the REPO service to also create a BSP hosting the adaptation.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an adaptation project
**when** I execute a command and answer a set of questions
**then** I will get a valid deployment configuration generated.

**Given** I have an adaptation project with a valid deployment config
**when** I execute a deploy command
**then** my project will be deployed.

### Tasks
- [x] enhance `deploy-tooling` to support adaptation projects 
- [x] enhance `create` to allow adding a deploy config to an adaptation project
- [ ] integrate the functionality back into the `@sap/adp-cli` 
- [x] unit Tests added
