### ISSUE TITLE
FEATURE - Enhance CPE with Add Fragment to Ext Point extension

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1360]
_As a developer,
I want to be able to enhance adaptation projects with a new type of change,
so that I can add fragments to extension points_

### Description

Visual Editor (for Adaptation Projects) has the functionality to add fragments to extension points, this needs to be available in Control Property Editor too.

### Technical Design
_What modules need to be created or enhanced?_ 
The following modules need to be enhanced:
`@sap-ux/control-property-editor`,
`@sap-ux/preview-middleware`,
`@sap-ux-private/preview-middleware-client`

_How would the functionality be exposed and how can it be consumed?_
It can be installed through npm.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project
**When** I right-click on the extension point in the outline tree or on a control, a context menu should appear with the option 'Add fragment to extension point'.
**Then** a dialog should open and I should be able to add a new XML fragment to that extension point.

### Tasks
- [x] Outline tree is enhanced with extension points in the Control Property Editor
- [x] A tooltip with a button appears when clicking on an extension point in the outline tree
- [x] A new dialog for extension points is created
- [x] Unit Tests added
- [ ] Test Cases defined
