### ISSUE TITLE
FEATURE - i18n module

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#1365]
### Description

Tools need to be able to read and write i18n entries for apps. There are various flavours of i18n files and we should have common way for handling all of them, that can be easily reused by tools. 

UI5 resource modules (properties files)
UI5 manifest.json translation entries (properties files)
CAP CDS services (properties, CSV and JSON files)

### Technical Design
_What modules need to be created or enhanced?_ 
New module `@sap-ux/i18n`
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ...
**when** I execute ...
**then** ... will happen.

### Tasks
- [ ] Parsers
  - [ ] properties
  - [ ] csv
  - [ ] json 
- [ ] CDS support
- [ ] UI5 support
- [ ] Consider mem-fs support?
- [ ] Use common function to get i18n properties in https://github.com/SAP/open-ux-tools/pull/1475/files#diff-f2599904e616ac2446bef03eb16046f806b7c637da5b005a856be5abf0228a9aR97
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by voicis** [comment]
Added in #1655
