### ISSUE TITLE
FEATURE - Add ui5 library prompting module

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#1389]
### Description

As a developer I want to build a generator for UI5 libraries. As such in addition to the already available `@sap-ux/ui5-library-writer` I need a way to gather user inputs from the CLI or other user interfaces that supports Inquier prompting format

### Technical Design

New modules:

- `@sap-ux/ui5-library-inquirer` (main entry point)
- `@sap-ux/ui5-info` (supporting module - allow retrieval and processing of UI5 version info for use by UI5 version prompts)

### Tasks
- [x] Add `ui5-info` : provides UI5 version info
- [x] Add new validators to `project-input-validators`
- [x] Add `ui5-library-inquirer`: prompt module for UI5 library generation
- [x] Unit Tests added
- [ ] Test Cases defined

**Comment by IainSAP** [comment]
Closing as completed
