### ISSUE TITLE
FEATURE - Open existing controller from project files instead of creating a new one

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1404]
_As a **developer**,
I want to **have new functionality for the adaptation projects**,
so that I **can reuse controller extension files for selected control**_

### Description

Visual Editor (for Adaptation Projects) can open the existing controller extension file (instead of creating a new one) when clicking 'Extend With Controller' from the context menu when right-clicking on a control.

### Technical Design
_What modules need to be created or enhanced?_ 
`@sap-ux/adp-tooling`,
`@sap-ux/preview-middleware`,
`@sap-ux-private/preview-middleware-client`

_How would the functionality be exposed and how can it be consumed?_
It can be installed through npm.
### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project
**when** I right-click on the context menu and choose 'Extend With Controller'
**then** ControllerExtension dialog will be opened with the text and a link: `Controller extension has already been created: Open file`. After clicking `Open file` the file will be opened in the VSCode application.

### Tasks
- [ ] An existing controller extension dialog is enhanced
- [ ] Existing controller extension file is opened in VSCode
- [ ] Unit Tests added
- [ ] Test Cases defined
