### ISSUE TITLE
FEATURE - Make Control Property Editor aware which application (scenario) its running in the iframe

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1414]
_As a **developer**,
I want to **have a distinction in CPE in which application is being used**,
so that I **can adjust the code according to the current scenario, enable or disable some features**_

### Description

Adaptation Projects have functionality that makes changes in CPE to the Outline Tree. Fiori applications should not have this feature enabled. And overall in the future, we need to have some distinction between different applications and whether we need to enable or disable some features.

### Technical Design
_What modules need to be created or enhanced?_ 
`@sap-ux/control-property-editor`,
`@sap-ux-private/control-property-editor-common`,
`@sap-ux/preview-middleware`,
`@sap-ux-private/preview-middleware-client`

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I run CPE with some application
**When** I open the editor
**Then** some features must be enabled/disabled depending on application type.

### Tasks
- [ ] CPE knows what application it is running, redux store is updated
- [ ] Unit Tests added
- [ ] Test Cases defined
