### ISSUE TITLE
TBI -  `@sap-ux/ui5-library-inquirer` should allow a prompting module reference to be used (from a generator, for example)

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#1444]
### Description (include screenshots)

`@sap-ux/ui5-library-inquirer` exports an api to provide prompting using it own an inquirer instance, as well as exporting the prompts array for use in any other prompting modules. When used in the context of a Yeoman generator it may be necessary to provide the generators inquirer instance  instead. For example when used in the context of YUI the inquirer instance (prompting module) needs to be the same or YUI will not recognise the prompts for UI rendering. While this can be worked around by using `getPrompts` , the consuming prompting module must then also register any plugins used by those prompts. This is not ideal and instead we can provide the prompting module reference to be used .

### Value
Less code in the consuming generator. Dependencies on any inquirer plugins will be encapsulated in the `@sap-ux/ui5-library-inquirer` and the consuming generator will not need to register them also.

### Architecture Elaboration
Does it requires architecture elaboration?

### Notes

`@types/inquirer@8.2.7` currently specified in `@sap-ux/ui5-library-inquirer` is wrong and should be 8.2.6. This would lead to tsc errors in the consumer when passing `promptModules` and  prompt function.

### Tasks
- [x] Add inquirer adaptor interface definition : 
```
export interface InquirerAdaptor {
    prompt: PromptFunction;
    promptModule: PromptModule;
}
```
- [x] Update prompt function signature to : `async function prompt(promptOptions?: UI5LibraryPromptOptions, adaptor?: InquirerAdaptor): Promise<UI5LibraryAnswers> `

- [x] Update `@types/inquirer@8.2.7` -> `@sap-ux/ui5-library-inquirer@8.2.6`
