### ISSUE TITLE
FEATURE - Allow deletion of a change file without respective controller extension from the dialog

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1460]
_As a **developer**,
I want to **be able to delete a change file without a respective controller extension file from dialog**,
so that I **can create a new controller extension file (only one controller extension is allowed per view)**_

### Description
When the user has a `codeExt` change file that points to a controller extension that does not exist, we need to give him/her the possibility to remove this change file. So, he can create a new controller extension file

### Technical Design
_What modules need to be created or enhanced?_ 
`adp-tooling`,
`preview-middleware`,
`preview-middleware-client`

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a working Adaptation Project
**when** I click `Extend With Controller` from the context menu
**then** a dialog will open from which I will be able to delete a change file (with no controller extension).

### Tasks
- [ ] Enhance the current dialog
- [ ] Enhance the adp-tooling route handler/s
- [ ] Unit Tests added
- [ ] Test Cases defined
