### ISSUE TITLE
FEATURE - Remove label and icon in control property editor

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1463]
_As an **tools developer**,
I want to **be able to integrate the control property editor without a name/logo**,
so that I **so that I can more freely use it**_

### Description

There is no need to have a name in the control property editor, its usage will be implied by the calling VSCode task or context menu entry or other link.

The browser tab will have no icon either and the document title will be: `Editing <app_name>`.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I start the control property editor
**when** it is started
**then** CPE will open and have no name and logo.

### Tasks
- [ ] Remove label and logo
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by voicis** [comment]
We still need to support both scenarios, when it is opened via VSCode and browser.
