### ISSUE TITLE
FEATURE - Enhance the error message for the user when he tries to create a new controller extension

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1467]
_As a **developer**,
I want to **see a more descriptive error message when trying to create controller extension**,
so that I **can see what options I have to get rid of the error**_

### Description

Need to enhance the error message for the user when he tries to create a new controller extension (but he already has a `codeExt` change file that points to a non-existing controller extension file).

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a working Adaptation Project and I run `npm run editor`
**when** I try to create a controller extension and it fails
**then** a message toast will appear with a more descriptive error message

### Tasks
- [ ] Enhance error message
- [ ] Unit Tests added
- [ ] Test Cases defined
