### ISSUE TITLE
FEATURE - Introduce confirmation deploy and undeploy prompt before executing the task

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1501]
_As a **developer**,
I want to **to be asked to deploy or undeploy my Fiori UI application**,
so that I **cancel if the properties are incorrect**_

_As a **developer**,
I want to **to be able to bypass the deploy or undeploy prompt**,
so that I **can create CI/CD pipeline jobs without any prompting**_

### Description

Deploy prompt
```
2023-11-27 17:21:17 info    abap-deploy-task: Creating archive from dist. 
2023-11-27 17:21:17 info    abap-deploy-task: Archive created from dist. 

Confirmation is required to deploy the app:

    Repository Entry: apps/cus.sd.salesorders.manage/appVariants/customer.adp.salesorder.manage3/
    Target: <my target URL>
    Transport Request: 
    Package: $TMP
    Client: 100
    Cloud: false

? Start deployment (Y/n)? › (Y/n)
```

Undeploy prompt
```
> customer-salesorders-adapt@0.1.0 undeploy
> undeploy --config ui5-deploy.yaml --lrep 'apps/cus.sd.salesorders.manage/appVariants/customer.adp.salesorder.manage3/'


Confirmation is required to undeploy the app:

    Repository Entry: apps/cus.sd.salesorders.manage/appVariants/customer.adp.salesorder.manage3/
    Target: <my target URL>
    Transport Request: 

? Start undeployment (Y/n)? › (Y/n)
```

### Technical Design
- Enhance the deploy-tooling module
- introduce a new dependency called `chalk` to handle the application info during the prompting phase

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a ui5-deploy.yaml configuration
**when** I execute `npm run deploy` or `npm run undeploy`
**then** I should be prompted with a confirmation page displaying application info before executing the task

**Given** I have a ui5-deploy.yaml configuration
**when** I execute `npm run deploy -- --yes` or `npm run undeploy -- --yes`
**then** I should be able to execute the task without any prompting

### Tasks
- [ ] Update deploy-tooling to support new prompting phase
- [ ] Unit Tests added
- [ ] Test Cases defined
