### ISSUE TITLE
FEATURE - Support ui5 version 1.71.* in CPE for Adaptation Projects

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1571]
_As a **developer**,
I want to **I want to be able to preview/edit it in VS Code and CPE with ui5 version 1.71.***,
so that I **can adapt the ADP to my business needs**_

### Description

_What is the high level purpose and value of the feature?  The description should ensure that anyone reading understands what it is doing (at a high level) and most importantly why._

Background and technical details: 1.71.* is currently not supported because of the lack of the fake connectors that are present in Visual Editor in BAS. These should be implemented similarly in CPE so preview and edit work while using this UI5 version.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an ADP with ui5 version 1.71.*
**when** I run the editor
**then** CPE should open and load the application in the iframe.

### Tasks
- [ ] FakeConnector is added and is used based on the current ui5 version.
- [ ] Unit Tests added
- [ ] Test Cases defined
