### ISSUE TITLE
FEATURE - Add new Jest matchers module

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#1617]
_As a **Fiori developer**,
I want to **use custom jest matchers**,
so that I **add them to my unit tests**_

### Description
This module will contain custom matchers to be used in tests. These custom matchers allow the consumer to extend its functionality to match specific requirements of the test cases

### Technical Design
New module `@sap-ux/jest-file-matchers` to be added. No dependency on other modules. 

### Acceptance Criteria
**Given** I have a unit test
**when** I make the matchers available in my tests
**then** I will have the option to use the custom matchers

### Tasks
- [ ] Create new module `@sap-ux/jest-file-matchers`
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by cianmSAP** [comment]
Feature added
