### ISSUE TITLE
FEATURE - Switch Adaptation Project's manifests editors/wizards to use Open Source writers

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1637]
_As a **developer**,
I want to **move part of the writing functionality to OS repository**,
so that I **can further make the writing identical independent of environment**_

### Description

_Wizards should be adjusted to use the common writers of Fiori Tools to further split the code and make the writing be independent of environment._

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project yeoman generators,
**when** I reuse the writing functionality and run the editor,
**then** writing will happen correctly.

### Tasks
- [ ] Enahnce writing module for adp-tooling to allow for manifest editors to reuse this functionality
- [ ] Unit Tests added
- [ ] Test Cases defined
