### ISSUE TITLE
(experimental) FEATURE - Middleware to create and edit integration cards

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1667]
_As a **developer**,
I want to **add a card to my application**,
so that it **can be used as another entry point to my app**_

### Description
The goal is to build a middleware that allows creating and editing cards. Since this is not yet commonly used, we also need a CLI command that enables a project for cards editing if requested by the developer.

### Technical Design
* a middleware attaching a card editor to a locally running app
* a module that enhances a project with the required middleware
* integration into the `create` module

### Acceptance Criteria
**Given** I have a UI5 application project
**when** I execute a command to add the middleware
**then** the project will be ready for creating cards.

**Given** I have a UI5 application project with the new middleware being added
**when** I execute a command to start the preview that includes my middleware
**then** I can create a card.

### Tasks
- [ ] add new modules
- [ ] integrate into `create`
- [ ] Unit Tests added
- [ ] Test Cases defined
