### ISSUE TITLE
TBI - Prepare preview middleware for UI5 2.0

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1679]
### Description (include screenshots)
Internal testing of the preview middleware with a preliminary version of UI5 2.0 has shown issues in the code. This ticket is to track (and solve) these issues.

### Value
Getting the preview middleware ready for UI5 2.0.

### Architecture Elaboration
All fixes are expected in the `preview-middleware-client` module

### Tasks
- [ ] `sap.ui.getCore().getConfiguration().getLanguage()` needs to be replaced, with `sap.ui.core.Configuration.getLanguage`
- [ ] `sap.ushell.Container` needs to be replaced with `sap.ui.require(“sap/ushell/Container”)`
- [ ] `sap.ushell.Container.createRenderer()` is also deprecated - however there is no production ready solution yet
- [ ] `sap.base.util.UriParameters` needs to be replaced with `sap/base/util/UriParameters`

**Comment by codeworrior** [comment]
Small corrections to avoid misunderstandings:
* [`sap.ui.getCore().getConfiguration().getLanguage()`](https://ui5.sap.com/#/api/sap.ui.core.Configuration%23methods/sap.ui.core.Configuration.getLanguage) needs to be replaced with [`import("sap/base/i18n/Localization").getLanguage`](https://ui5.sap.com/#/api/module:sap/base/i18n/Localization%23methods/sap/base/i18n/Localization.getLanguage)
* [sap/base/util/UriParameters.fromQuery(...)](https://ui5.sap.com/#/api/module:sap/base/util/UriParameters%23methods/sap/base/util/UriParameters.fromQuery) needs to be replaced with the native [new URLSearchParams(...)](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)

**Comment by zdravko-georgiev** [comment]
For FLP Sandbox and UI5 2.0 we've discussed the following options:

1. We explicitly expect the user to tell us
    - We add a new config property to the preview-middleware of type boolean allowing to switch to the new sandbox
    - We add a url parameter with the same effect
    - We add a env variable with the same effect
1. We add a handler for both urls to the preview-middleware and if either of them returns a 404, we just redirect to the other. Tricky part here: we don’t know if the preview middleware is executed before or after the ui5-proxy middleware (or any other that might be serving the sources)
1. We create our own bootstrap script that checks the UI5 version and then depending on the result pick one or the other

The decision is to go for option 3.
