### ISSUE TITLE
FEATURE - Saving all changes when adding fragments ext in CPE

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1684]
_As a **persona**,
I want to **the change file to be automatically saved after creating the change**,
so that **it is consistent with the xml file being created for the change**_

### Description

_Currently, when a a developer creates fragment the related changes are not automatically saved to the workspace but the actual xml or js files are saved which may lead to inconsistencies between changes and related files._

_Also, IF there are currently UNSAVED changes in the CPE , I want to be notified with a label starting with info icon above the 'Create' button in the adding fragments dialog saying "Have in mind that adding this change will also save the changes you have made to your project that are yet unsaved"_

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an ADP
**when** I add an XML fragment
**then** the change file and the XML fragment are saved at the same time right away.

### Tasks
- [ ] Enhance Add Fragment dialog
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
I agree to the problem but I'd like to challenge the suggested solution. Instead of saving automatically, we shouldn't write the fragment to the filesystem right away but just keep it in the mem-fs for example and ONLY save it when the corresponding change is saved.

**Comment by nikmace** [comment]
> I agree to the problem but I'd like to challenge the suggested solution. Instead of saving automatically, we shouldn't write the fragment to the filesystem right away but just keep it in the mem-fs for example and ONLY save it when the corresponding change is saved.

It was done like this #1625 at the start but then the PR got closed, don't remember why we decided not to do it.

**Comment by nikmace** [comment]
> I agree to the problem but I'd like to challenge the suggested solution. Instead of saving automatically, we shouldn't write the fragment to the filesystem right away but just keep it in the mem-fs for example and ONLY save it when the corresponding change is saved.

Actually, here we are talking not about the XML fragments but the respective change files and the flow. For example, when clicking the create button for the Add Controller dialog, the change and the .js file are created and saved after the button click. The Add Fragment dialog, on the other hand, creates a command that is then pushed to the stack and executed.

There is a third solution to this. The command itself offers API that can be called and the change file can be generated.
<img width="1549" alt="Screenshot 2024-02-05 at 10 10 20" src="https://github.com/SAP/open-ux-tools/assets/39880364/10b41ba2-f886-4c93-b41a-a69ad1b9b562">
