### ISSUE TITLE
FEATURE - Support typescript in adaptation projects

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1685]
_As a **develop**,
I want to **write a controller extension in an adaption project in typescript**,
so that I **can enjoy the pleasures of typescript**_

### Description
Similar to Fiori applications, we also need to add typescript support for adaptation projects.

### Technical Design
This requires changes in multiple stages of the development flow
1. Generation
2. Preview
3. Editing i.e. adding a controller extension

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I want to use typescript 
**when** I execute the adaptation project generator 
**then** an adaptation project is generated allowing me to add controller extensions in typecript and everything works as usual.

### Tasks
- [ ] Enhance preview to support typescript projects
- [ ] Enhance generator to enable typescript (check reuse of existing functionality in `ui5-application-writer`
- [ ] Modify the controller extension feature to generate typescript files if the project is typescript enabled
- [ ] Everything is properly tested
