### ISSUE TITLE
TBI - Consolidation of common functionality across writer modules

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#170]
### Description (include screenshots)
With the release of the initial `0.x` versions of our writers we have ensured that the public APIs are sound and that the modules are functionally correct. However, we left some room for improvements of inner implementations. This TBI is to track some of the things that should be fixed before the repository grows with further modules.

### Value
Improve maintainability by consolidating and aligned the implementations of the existing modules

### Architecture Elaboration
- TBD: common i18n approach 
- TBD: central ui5 types collection

### Notes
@devinea this is the follow up to some of the comments from your review for #39 

### Tasks
- [ ] All modules use the `webapp` folder as a hardcoded folder name containing the UI5 application. This assumption does not always have to be fulfilled, therefore, the code, especially of the `odata-service-writer` and the `fe-fpm-writer` need to be adapted to be more flexible
- [ ] Thrown errors are sometimes but not always internationalized in our modules. We need to consistently internationalize all strings that are possibly visible to an end-user
- [ ] define the types required to work with a `manifest.json` in one place and use it across modules
