### ISSUE TITLE
FEATURE - Support HTML page to run OPA tests in the `preview-middleware`

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1706]
_As a **developer**,
I want to **use the `preview-middleware` for my OPA tests**,
so that I **don't have to maintain a test specific html file in my project.**_

### Description
We have the goal to remove as many as possible of the `html` files in the `webapp/test` folder and maintain them centrally in the `preview-middleware`. With this feature, we want to remove everything generic required for running OPA tests.

### Technical Design
* enhance the init script to also execute an additional script after initialization to start the OPA tests
* enhance the middleware configuration to additional offer an OPA test page
   * already keep in mind we might add other test frameworks in the future e.g. WDI5  
* create an OPA template (or something to be injected into the existing template) 

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a OPA tests in my project but no `opaTests.qunit.html` in my project folder
**when** I execute my test script
**then** the tests will be properly executed.

### Tasks
- [x] add option for a custom init script
- [x] add options for an OPA test file exposure
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by tobiasqueck** [comment]
Requested functionality was contributed by @heimwege with #1726!
