### ISSUE TITLE
TBI - update `mem-fs` and `mem-fs-editor`

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#1716]
### Description (include screenshots)
We're currently using `mem-fs-editor` version `9.4.0` which is 2 years old now and the latest version is `11.0.0`. We should update it to the latest version.

### Value
Maintenance and upkeep.

### Tasks
- [ ] update `mem-fs` and `mem-fs-editor` version
- [ ] remove @types/mem-fs* modules
- [ ] update imports of type Editor it is now MemFsEditor
- [ ] manually checking the API changes - on first glance it looks like there are a few e.g. read returns string | null instead of just string and copyTpl has different input parameters.
