### ISSUE TITLE
TBI - set `"strict": true` in `tsconfig.json`

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#1741]
### Description
We would like to enable strict mode for all our modules in tsconfig.json.
We've identified modules that have strict: false in tsconfig.json:
```
examples/odata-cli/tsconfig.json:
  9:         "strict": false

packages/axios-extension/tsconfig.json:
  10:     "strict": false

packages/environment-check/tsconfig.json:
  10:         "strict": false

packages/feature-toggle/tsconfig.json:
  7:         "strict": false

packages/jest-file-matchers/tsconfig.json:
  7:         "strict": false

packages/jest-runner-puppeteer/tsconfig.json:
  7:         "strict": false
```

### Value
Improve code quality

### Tasks
- [ ] examples/odata-cli/tsconfig.json
- [ ] packages/axios-extension/tsconfig.json
- [ ] packages/environment-check/tsconfig.json
- [ ] packages/feature-toggle/tsconfig.json
- [ ] packages/jest-file-matchers/tsconfig.json
- [ ] packages/jest-runner-puppeteer/tsconfig.json
