### ISSUE TITLE
FEATURE - Allow adding tiles pointing to remotely available apps in the preview-middleware

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1763]
_As a **developer**,
I want to **add existing applications to my FLP preview**,
so that I **can test app to app navigation**_

### Description
When testing my application in the FLP preview, I also want to test app-to-app navigation. Assuming I am using also the `backend-proxy-middleware` my app would be available, and I just want to add it as tile to the FLP preview with a configuration like the one below (which doesn't point to a backend but a sample app included in UI5).

```yaml
apps
  - target: /test-resources/sap/ushell/demoapps/AppNavSample
    componentId: sap.ushell.demo.AppNavSample
    intent: 
      object: TheOther
      action: preview
```

### Technical Design
Enhance the support for additional tiles to also allow adding apps not available locally but remotely.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a project with the preview-middleware and backend-proxy-middleware
**when** I add a config like the one in description
**then** I have a tile that points to my remote application.

### Tasks
- [x] Implement the feature
- [x] Unit Tests added
- [x] Test Cases defined
