### ISSUE TITLE
[Security] `follow-redirects` Information Exposure

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1767]
### Description
`follow-redirects` is an open source, drop-in replacement for Node's http and https modules that automatically follows redirects. In affected versions follow-redirects only clears authorization header during cross-domain redirect, but keep the proxy-authentication header which contains credentials too. This vulnerability may lead to credentials leak, but has been addressed in version 1.15.6. Users are advised to upgrade. There are no known workarounds for this vulnerability.

More information at https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6444610

### Tasks
- [ ] user overrides to remove the nested dependencies to the vulnerable version (#1766)
- [ ] Remove  "nx-cloud>axios@<1.6.8": ">=1.6.8" as soon as possible
- [ ] Remove  "@sap/bas-sdk>axios@<1.6.8": ">=1.6.8"as soon as possible
- [ ] Remove  "http-proxy>follow-redirects@<1.15.6": ">=1.15.6"as soon as possible
- [ ] Remove "socks-proxy-agent>socks@<2.8.1": ">=2.8.1"as soon as possible
- [ ] Remove  "ip@<2.0.1": ">=2.0.1" as soon as possible
