### ISSUE TITLE
FEATURE - Read toolsId from Adaptation Projects ui5.yaml file in telemetry package

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1847]
_As a **developer**,
I want to **collect per project telemetry for ADP**,
so that I **can see how the CPE is being used**_

### Description

_We need the toolsId to differentiate between created projects to collect telemetry on how it is used_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project with a valid ui5.yaml
**when** I can extract the missing data for telemetry initialization
**then** it can be sent as a report to the dashboard.

### Tasks
- [ ] Read the toolsId from ui5.yaml
- [ ] Unit Tests added
- [ ] Test Cases defined
