### ISSUE TITLE
FEATURE - Add fiori generator shared module

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#1850]
_As a developer,
I want to have a central module for functions used by the fiori generator,
so that I reuse these functions in my development_

### Description
With future additions of the Fiori generator and it's sub-generators, there is a need for a central module to contain the functions which can be shared across the modules

### Technical Design

`@sap-ux/fiori-generator-shared`

### Tasks
- [ ] Add function for reading cap custom paths
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by cianmSAP** [comment]
Closing as module is published
