### ISSUE TITLE
FEATURE - Add default content for extension points to the outline in CPE 

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#1866]
_As a **developer**,
when I **am using CPE and have opened an ADP containing ext points**,

I want to **see their default content in the outline tree and the message that explains about that default content in the 'add new fragment' dialog in the same manner as in VE**,

so that I **know what is the default content of an ext point that I would be replacing If I add fragment to it and to be notified that this default content will no longer be there after the replacement**._

### Description

_The developer can see the existing default content under an extension point in the outline tree and he is notified about it in the 'add new fragment' dialog in the same manner as in VE._

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an ADP with Extension Points that have default content,
**when** I open the Add Fragment at Extension Point dialog
**then** I see a message notifying me that if I continue to add a fragment I will no longer see the fragment.

### Tasks
- [ ] Enance CPE with default content
- [ ] Unit Tests added
- [ ] Test Cases defined
