### ISSUE TITLE
FEATURE - enable UI service generation and publishing via new axios-extension services

### ISSUE THREAD

**Issue by docirl** [SAP/open-ux-tools#1893]
### Description

Create new adt services to enable a user to generate and publish a ui service, using ADT api's via the adt discovery service.

### Technical Design
New adt services in axios extension will expose the discovery endpoints that are required:
- retrieve a list of business objects from the target system
- generate the ui service
- publish the ui service

### Acceptance Criteria

**Given** I have a target system with required user role to generate a service
**when** I call the new adt services in the correct sequence
**then** a ui service will be generated and published to on the target system

### Tasks
- [ ] Create new adt services for generation and publishing
- [ ] Add sample to examples/odata-cli to document sequence for calling the api's.
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by docirl** [comment]
Completed
