### ISSUE TITLE
TBI - Add additional cap configuration writing functionalities to @sap-ux/cap-config-writer

### ISSUE THREAD

**Issue by kjose90** [SAP/open-ux-tools#1908]
### Description (include screenshots)
Will automatically update the following files on generating a cap application - 

- application level package.json, root level package.json
- manifest.json
- tsconfig.json
- application.yaml
- pom.xml
- annotation.cds 
- ui5.yaml

### Architecture Elaboration
Yes

### Notes
removeFioriToolsProxyAndAppReload() is a part of cap application writer, which have been moved to ```@sap-ux/ui5-config```
Add package read and get package path functionalities to ```@sap-ux/fiori-generator-shared```

### Tasks
- [X] Update project-access to return cds version: https://github.com/SAP/open-ux-tools/issues/1934
- [X] Update odata-service-inquirer to return cds version : https://github.com/SAP/open-ux-tools/issues/1934
- [X]  Update open-ux-tools writers odata-service-writer to allow writing of cds or xml annotations: https://github.com/SAP/open-ux-tools/issues/1949
- [X]  Update open-ux-tools writers to not call backend if application is cap
- [ ]  Update open-ux-tools to not write `ui5-local.yaml`, `.gitignore` and `webapp/index.html `if application is cap
- [ ]  Move `applyCapUpdates` and apply `applyCAPJavaUpdates` functions to cap-config-writers

**Comment by kjose90** [comment]
Closing Issue as this is done.
