### ISSUE TITLE
FEATURE - Utilize the UI5 linter

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#1938]
_As a **developer**,
I want to **be able to easily check my UI5 projects for UI5 2.x readiness**,
so that I **my projects are ready for future versions.**_

### Description
With the release of https://github.com/SAP/ui5-linter there is now a way to check if best practices in UI5 apps are applied. This is especially important to get ready for [UI5 2.x](https://community.sap.com/t5/open-source-blogs/introducing-openui5-2-x/ba-p/13580633).
To enable Fiori tools user, we should add the new linter as dev dependency and also add a script e.g. `lint:2.0` to our generated projects. 

### Technical Design
* enhance `ui5-application-writer` and `ui5-library-writer`
* add devDependency `@sap/ui5-linter`
* add script `"lint-2.0": "ui5lint "`

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a generate a UI5 application or library with the Fiori tools
**when** I execute `npm run lint-2.0`
**then** I will know what I have to do to make my project is 2.x compatible

### Notes
Experts for further discussion: @petermuessig and @RandomByte

### Tasks
- [ ] Enhance `ui5-application-writer`
- [ ] Enhance `ui5-library-writer`
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
After talking to @Klaus-Keller, I have decided to close my feature request, since it is already provided as tile in the application info page in the SAP Fiori tools. Everyone who is not using the tools, can just execute `npx --yes @ui5/linter@latest` manually, so there is no real benefit in adding the script.

![70dc1510-ceae-4384-910b-fc8a7a13d456](https://github.com/SAP/open-ux-tools/assets/44933199/7c44c184-2c70-4afd-9b84-d2f100ada37f)
