### ISSUE TITLE
TBI - To support the exclusion of middleware from ui5 yaml for cap projects

### ISSUE THREAD

**Issue by kjose90** [SAP/open-ux-tools#1955]
### To support the exclusion of middleware from ui5 yaml for cap projects
Giving an option as part of ui5 application writter to exclude the writing of middlewares into ui5 yaml files.
excludeMiddleware option is set to true for cap projects.

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Add `excludeMiddleware` to interface `AppOptions` in ui5 application writer
- [ ] Add logic to exclude the writing of middlewares when `excludeMiddleware` is true
- [ ] Add unit tests to ui5 application writer

**Comment by kjose90** [comment]
Closing this issue. Decision was made to leave proxy middleware and app reloads for cap project.
