### ISSUE TITLE
FEATURE - Define common logic for the retrieval of minUI5Version from manifest

### ISSUE THREAD

**Issue by schreckstefan** [SAP/open-ux-tools#1988]
_As a developer,
I want to retrieve the `minUI5Version` from manifest,
so that I can establish any logic that check against this minimum version of SAP UI5._

### Description

The `minUI5Version` is evaluated at various places of the SAP UX tools-suite. Traditionally it is defined in a string format in the ui5/dependencies section of the manifest. 
But there is an enhancement with https://www.npmjs.com/package/@ui5/manifest/v/1.65.1 that alternatively allows the definition of an array. The question now is how to handle such an array definition, as all applications currently expect a string value.
The agreement is to work with the minimum version of the array in this case.
But we should think about future enhancements that give the user the freedom to decide, e.g. for preview or run configurations.
Information pages could also show all options.

To be open for all possible use cases, the following set of functions should be provided:

- `getMinUI5VersionFromManifest` retrieves the value as it is defined in manifest, returns `string | string[]`.
- `getMinUI5VersionAsArray` converts the string value into an array, returns `string[]`.  Can be based on `getMinUI5VersionFromManifest`.
- `getMinimumUI5Version` returns the minimum version from an array-like definition, or any string value as is. Always returns `string`. Can be based on `getMinUI5VersionAsArray`.

### Technical Design
The functions shall be part of `project-access` module.
All given access routines to manifest are part of `packages/project-access/src/library/helpers.ts,` thus the new functions shall be placed here as well.

### Acceptance Criteria

**Given** I have a minUI5Version in string format:
      **when** I execute `getMinUI5VersionFromManifest` or  `getMinimumUI5Version`
      **then** I get the string value back;
      **when** I execute  `getMinUI5VersionAsArray` 
      **then** I get the string value back as entry of an array.

**Given** I have a minUI5Version in array format and it comprises only one entry (*):
 **when** I execute `getMinUI5VersionFromManifest` or `getMinUI5VersionAsArray` 
 **then** I get the string value back as entry of an array;
  **when** I execute `getMinimumUI5Version`
  **then** I get the string value back;

**Given** I have a minUI5Version in array format and it comprises multiple entries:
 **when** I execute `getMinUI5VersionFromManifest` or `getMinUI5VersionAsArray` 
 **then** I get the array back;
  **when** I execute `getMinimumUI5Version`
  **then** I get the string value back that corresponds to minimum UI5 version of the array;

### Notes
(*) This is invalid, according to the app descriptor definition, but can be handled in a fault-tolerant manner

### Tasks
- [x] Implement the new helper functions
- [x] Unit Tests added
- [ ] Test Cases defined

**Comment by schreckstefan** [comment]
Functions implemented, request fulfilled
