### ISSUE TITLE
FEATURE - Add Adaptation Project's Change Data Source generator prompting

### ISSUE THREAD

**Issue by mmilko01** [SAP/open-ux-tools#2002]
_As a **developer of an Adaptation Project**,
I want to **change the data source of a base application**,
so that I **can consume different OData source in a new application variant**_

### Description

After creating an Adaptation Project for a give base application, we can utilize a new feature to change the OData source consumed by the application, so that the resulting application variant can consume different OData source.

This feature provides a CLI command `sap-ux change data-source` that starts a prompting guiding us in the process of changing the data source.

### Technical Design
* enhance the `adp-tooling`
  * add prompting relevant to change data source functionality in an Adaptation Project
  * add new function for fetching the manifest.json of the base application
* enhance the `axios-extension`
  * add function for fetching the /ui5_app_info_json for a specific application ID, which is needed to find URI of the base application 
    manifest.json
* enhance the `create`
  * add CLI command `sap-ux change data-source <path>`

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project that needs to change the data source of the base application
**when** I execute `sap-ux change data-source <path>`
**then** prompting for specifying the new data source is started and after finished results in new change files in `changes` directory of the Adaptation Project 

### Tasks
- [ ] 
- [ ] Add prompting to `adp-tooling`
- [ ] Add function for fetching the base application manifest.json to `adp-tooling`
- [ ] Add new function of fetching ui5_app_info_json to `axios-extension`
- [ ] Add CLI command to `create` 
- [ ] Unit Tests added
- [ ] Test Cases defined
