### ISSUE TITLE
TBI - Support UICombobox with virtualization(VirtualizedComboBox from fluentui)

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#2018]
### Description (include screenshots)
Allow to create Combobox with virtualized list.
`fluentui` already supports it, but as separate component -> https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox
check for `VirtualizedComboBox`

### Value
When we have large lists(around 1k entries) - opening and scrolling behaviour is not so smooth - in result we should allow to enable virtualization for dropdown list

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Enahnce `UICombobox` with new property `virtualized`
- [ ] Apply `VirtualizedComboBox` if `virtualized` property is enabled
- [ ] Adjust logic of  `UICombobox` if necessary

**Comment by 815are** [comment]
https://github.com/SAP/open-ux-tools/pull/2059
