### ISSUE TITLE
TBI - Add generate readme functionalities to fiori generator shared

### ISSUE THREAD

**Issue by kjose90** [SAP/open-ux-tools#2019]
### Description (include screenshots)
The addition of generate readme functionalities to the `@sap-ux/fiori-generator-shared` module provides developers with an automated tool to generate README files. 

### Tasks
- [ ] Move logic to compose read me file 
- [ ] Move generate read me logic to  `fiori-generator-shared` https://github.com/SAP/open-ux-tools/pull/2022
- [ ] Move support to get launch text for cap projects in `cap-config-writers` https://github.com/SAP/open-ux-tools/pull/2043
- [ ] add unit tests

**Comment by kjose90** [comment]
Initially, the plan was to transfer the readme generation logic to the `ui5-application-writer` module. However, it became evident that the readme template makes use of generator-specific variables. Therefore, it was seemed more appropriate to integrate this logic into the `fiori-generator-shared` module.

**Comment by kjose90** [comment]
Closing this this issue. Done.
