### ISSUE TITLE
TBI - Improve consistency and documentation of authentication handling across middlewares and tasks

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#2029]
### Description (include screenshots)
While being at UI5Con, I have noticed that our documentation about how we handle authentication across the tools has room for improvements. On the one hand, it is not clearly documented and on the other hand, there are subtle differences between the middlewares that need to be aligned.

### Value
A clear documentation helps consumers to better utilize the tools, and a consistent behavior is the expectation of consumers.

### Architecture Elaboration
n/a

### Tasks
- [ ] Add handling of Fiori tools CI/CD variables to the `system-access` module to be consistent with the `backend-proxy-middleware`
- [ ] Evaluate using `system-access` in the `backend-proxy-middleware`
- [ ] Enhance the READMEs of `system-access` and all its consumers to clearly explain how authentication is handled

**Comment by marianfoo** [comment]
I want to add that the debug parameter in the deploy tasks is documented neither in help.sap nor in the readme. It's in the readme for the deploy task itself which was linked in the console after I experienced a error.

Also in the help.sap there is a tip to use `DEBUG=ux-odata-client npm run deploy`. Does that work?  
https://help.sap.com/docs/SAP_FIORI_tools/17d50220bcd848aa854c9c182d65b699/1b7a3be8d99c45aead90528ef472af37.html?locale=en-US&q=Debug
