### ISSUE TITLE
TBI - Exclude writing of specific files for CAP applications

### ISSUE THREAD

**Issue by kjose90** [SAP/open-ux-tools#2031]
### Description (include screenshots)
When the application is a CAP, ensure the following files are not added:
- `.gitignore`
- `ui5-local.yaml`
- `./webapp/index.html`

### Tasks
- [ ] Add a flag in `ui5-application-writer` to check if the application is CAP. If true, do not copy `.gitignore` and `ui5-local.yaml `from templates. Also, exclude the `start-local `script in the package.json.
- [ ] Do not write `ui5-local.yaml `if the service is of CDS type in `odata-service-writer`.
- [ ] Set a flag in `fiori-elements-writer` (to be passed to sub modules) to indicate that the application is CAP. If true, exclude the `start-local `script in the package.json tasks.
- [ ] Set a flag in `fiori-freestyle-writer` to indicate that the application is CAP. If true, exclude the` start-local `script in the package.json tasks.
- [ ] Update relevant snapshots in all modules to reflect changes for CAP applications.

**Comment by kjose90** [comment]
Closing this this issue. Done.
