### ISSUE TITLE
TBI - UI Service Generator - use new api endpoint

### ISSUE THREAD

**Issue by docirl** [SAP/open-ux-tools#2063]
### Description (include screenshots)
The UI Service generator should now point to the new api endpoint (that contain `webapi/published-ui-service`)
The endpoints are returned by adding `type=webapi` to the existing call to get the generator for a BO.
The new api will now generate and publish the service in one call, so the publish service is no longer needed and should be removed

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Update method to get the generator config to include a new param `type=webapi`, this will retrieve the config with the new endpoints
- [ ] Add additional endpoints for validating package and content to the ui service generator methods
- [ ] remove publish methods and associated code

**Comment by docirl** [comment]
Done in https://github.com/SAP/open-ux-tools/pull/2064
