### ISSUE TITLE
FEATURE - Add Adaptation Project's OData Service and SAPUI5 Model prompting

### ISSUE THREAD

**Issue by nikmace** [SAP/open-ux-tools#2082]
_As a **developer of an Adaptation Project**,
I want to **add odata service and sapui5 model**,
so that I **can manipulate the app manifest**_

### Description

After creating an Adaptation Project for a given base application, we can utilize a new feature to add the OData Service and SAPUI5 Model.

This feature provides a CLI command `sap-ux change new-model`.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project that needs to add the OData Service and SAPUI5 Model to the base application
**when** I execute `sap-ux change new-model <path>`
**then** prompting is started and after finishing, results in a new change file in the `changes` directory of the Adaptation Project appear.

### Tasks
- [ ] Add prompting to `adp-tooling`
- [ ] Add CLI command to `create` 
- [ ] Unit Tests added
- [ ] Test Cases defined
