### ISSUE TITLE
FEATURE - Add Adaptation Projects' Add Annotations To OData generator prompting

### ISSUE THREAD

**Issue by mmilko01** [SAP/open-ux-tools#2119]
_As a **developer of an Adaptation Project**,
I want to **add an annotation to the odata of a base application**,
so that I **add information and hints to the EDM elements**_

### Description

After creating an Adaptation Project for a give base application, we can utilize a new feature to add annotation to the odata service consumed by the application.

This feature provides a CLI command `sap-ux add annotations` that starts a prompting guiding us in the process of adding annotations to odata service.

### Technical Design
* enhance the `adp-tooling`
  * add prompting relevant to add annotations to odata functionality in an Adaptation Project
* enhance the `create`
  * add CLI command `sap-ux add annotations-to-odata <path>`

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an Adaptation Project that needs to add annotation to the odata service of the base application
**when** I execute `sap-ux add annotations <path>`
**then** prompting for specifying the new annotations file is started and after finished results in new change files in `changes` directory of the Adaptation Project 

### Tasks
- [ ] 
- [ ] Add prompting to `adp-tooling`
- [ ] Add CLI command to `add` 
- [ ] Unit Tests added
- [ ] Test Cases defined
