### ISSUE TITLE
FEATURE - Align generated views in the basic Fiori freestyle with best practices in UI5

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#214]
_As a **developer**,
I want to **create a basic Fiori freestyle application that follows UI5 best practices**,
so that I **can use it as a starting point for application developmnent**_.

### Description
Reported by @lboehm at https://github.com/ui5-community/generator-ui5-project/issues/21 and affecting the `fiori-freestyle-writer`:

> I've created a sample repo with different branches. For each scenario I've created an PR inside my sample repo, so you can check what I've changed.
>
>The master branch is just an app that was generated with easy-ui5.
>
>The new-structure-initial branch is my proposal how easy-ui5 should generate an initial app.
>
>You can view the changes in this pull request. It's really not that much.
>And when easy-ui5 is generating apps as I propose, you may wonder what easy-ui5 would have to generate to add new views to an existing project. The new-structure-detail-view branch shows exactly that.
>
>You can view the changes in this pull request. (Nevermind the formatter.js, I should update easy-ui5 as vobu provided a fix for that already 😃)
>Basically it's no difference to what easy-ui5 generates today. Just the structure of the newly generated view should be different, because we don't need the <App> tag (see line 4 in the DetailView file)

from https://github.com/ui5-community/generator-ui5-project/issues/21#issuecomment-989027062

### Technical Design
For `worklist` and `listdetail` we already use the app-view -> page-view concept, therefore, also using it for the basic app makes a lot of sense purely from a consistency perspective even if it makes the basic app slightly more complex.

@petermuessig also approved this change at https://github.com/ui5-community/generator-ui5-project/issues/21#issuecomment-992319030

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a an empty folder
**when** I execute the `fiori-freestyle-writer` and choose the basic template
**then** the new structure with an application and main view is generated.

### Tasks
- [x] Modify the templates and the generation code
- [x] Modify test snapshots to match the new structure
- [x] Notify the Fiori tools team so that they can integrate the new version into the Fiori generator

**Comment by lboehm** [comment]
Hi @tobiasqueck,

I've tried to fix that issue, but I ran into some problems. `pnpm install` went fine:

```
C:\git\github\open-ux-tools>pnpm install
Scope: all 7 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +707
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\A002220\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Downloading registry.npmjs.org/typescript/4.4.4: 11 MB/11 MB, done
Progress: resolved 707, reused 0, downloaded 707, added 707, done

devDependencies:
+ @changesets/cli 2.18.0
+ @types/jest 27.0.2
+ @typescript-eslint/eslint-plugin 5.3.0
+ @typescript-eslint/parser 5.3.0
+ eslint 8.2.0
+ eslint-config-prettier 8.3.0
+ eslint-import-resolver-typescript 2.5.0
+ eslint-plugin-import 2.25.2
+ eslint-plugin-jsdoc 37.0.3
+ eslint-plugin-prettier 4.0.0
+ eslint-plugin-promise 5.1.1
+ husky 7.0.4
+ jest 27.3.1
+ prettier 2.4.1
+ pretty-quick 3.1.1
+ rimraf 3.0.2
+ ts-jest 27.0.7
+ ts-node 10.4.0
+ typescript 4.4.4

. prepare$ husky install
. prepare: husky - Git hooks installed
. prepare: Done
```

But when executing `pnpm test -- test/basic.test.ts` it fails:

```
C:\git\github\open-ux-tools\packages\fiori-freestyle-writer>pnpm test -- test/basic.test.ts
Debugger attached.

> @sap-ux/fiori-freestyle-writer@0.10.12 test C:\git\github\open-ux-tools\packages\fiori-freestyle-writer
> jest --ci --forceExit --detectOpenHandles --colors "test/basic.test.ts"

Debugger attached.
 FAIL  test/basic.test.ts
  ● Test suite failed to run

    test/basic.test.ts:5:30 - error TS2307: Cannot find module '@sap-ux/odata-service-writer' or its corresponding type declarations.

    5 import { OdataVersion } from '@sap-ux/odata-service-writer';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    test/basic.test.ts:15:13 - error TS2322: Type '{ id: string; title: string; description: string; flpAppId: string; }' is not assignable to type 'FioriApp'.
      Object literal may only specify known properties, and 'id' does not exist in type 'FioriApp'.

    15             id: 'nods1',
                   ~~~~~~~~~~~

      src/types.ts:41:5
        41     app: FioriApp;
               ~~~
        The expected type comes from property 'app' which is declared here on type 'FreestyleApp<BasicAppSettings>'
    test/basic.test.ts:90:17 - error TS2322: Type '{ id: string; }' is not assignable to type 'FioriApp'.
      Object literal may only specify known properties, and 'id' does not exist in type 'FioriApp'.

    90                 id: 'my.demo.App'
                       ~~~~~~~~~~~~~~~~~

      src/types.ts:41:5
        41     app: FioriApp;
               ~~~
        The expected type comes from property 'app' which is declared here on type 'FreestyleApp<any>'
    test/basic.test.ts:113:17 - error TS2322: Type '{ id: string; }' is not assignable to type 'FioriApp'.
      Object literal may only specify known properties, and 'id' does not exist in type 'FioriApp'.

    113                 id: 'someId'
                        ~~~~~~~~~~~~

      src/types.ts:41:5
        41     app: FioriApp;
               ~~~
        The expected type comes from property 'app' which is declared here on type 'FreestyleApp<BasicAppSettings>'

Running coverage on untested files...Failed to collect coverage from C:\git\github\open-ux-tools\packages\fiori-freestyle-writer\src\defaults.ts
ERROR: src/defaults.ts:9:43 - error TS2339: Property 'id' does not exist on type 'FioriApp'.

9     app.flpAppId = app.flpAppId || `${app.id.replace(/[-_.]/g, '')}-tile`;
                                            ~~
STACK: 
Failed to collect coverage from C:\git\github\open-ux-tools\packages\fiori-freestyle-writer\src\index.ts
ERROR: src/index.ts:4:57 - error TS2307: Cannot find module '@sap-ux/ui5-application-writer' or its corresponding type declarations.

4 import { generate as generateUi5Project, Package } from '@sap-ux/ui5-application-writer';
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/index.ts:5:45 - error TS2307: Cannot find module '@sap-ux/odata-service-writer' or its corresponding type declarations.

5 import { generate as addOdataService } from '@sap-ux/odata-service-writer';
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/index.ts:23:15 - error TS2339: Property 'baseComponent' does not exist on type 'FioriApp'.

23     ffApp.app.baseComponent = ffApp.app.baseComponent || 'sap/ui/core/UIComponent';
                 ~~~~~~~~~~~~~
src/index.ts:23:41 - error TS2339: Property 'baseComponent' does not exist on type 'FioriApp'.

23     ffApp.app.baseComponent = ffApp.app.baseComponent || 'sap/ui/core/UIComponent';
                                           ~~~~~~~~~~~~~
src/index.ts:33:5 - error TS2532: Object is possibly 'undefined'.

33     fs.copyTpl(join(tmplPath, 'common', 'add', '**/*.*'), basePath, ffApp);
       ~~
src/index.ts:35:5 - error TS2532: Object is possibly 'undefined'.

35     fs.copyTpl(join(tmplPath, ffApp.template.type, 'add', `**/*.*`), basePath, ffApp, undefined, {});
       ~~
src/index.ts:40:9 - error TS2532: Object is possibly 'undefined'.

40         fs.copyTpl(join(tmplPath, ffApp.template.type, 'custom/View.xml'), viewTarget, ffApp);
           ~~
src/index.ts:42:9 - error TS2532: Object is possibly 'undefined'.

42         fs.copyTpl(join(tmplPath, ffApp.template.type, 'custom/Controller.js'), controllerTarget, ffApp);
           ~~
src/index.ts:50:5 - error TS2532: Object is possibly 'undefined'.

50     fs.extendJSON(manifestPath, JSON.parse(render(fs.read(join(extRoot, 'manifest.json')), ffApp)));
       ~~
src/index.ts:50:51 - error TS2532: Object is possibly 'undefined'.

50     fs.extendJSON(manifestPath, JSON.parse(render(fs.read(join(extRoot, 'manifest.json')), ffApp)));
                                                     ~~
src/index.ts:53:5 - error TS2532: Object is possibly 'undefined'.

53     fs.append(
       ~~
src/index.ts:55:16 - error TS2532: Object is possibly 'undefined'.

55         render(fs.read(join(extRoot, 'i18n', 'i18n.properties')), ffApp)
                  ~~
src/index.ts:60:5 - error TS2532: Object is possibly 'undefined'.

60     fs.extendJSON(packagePath, JSON.parse(render(fs.read(join(tmplPath, 'common', 'extend', 'package.json')), ffApp)));
       ~~
src/index.ts:60:50 - error TS2532: Object is possibly 'undefined'.

60     fs.extendJSON(packagePath, JSON.parse(render(fs.read(join(tmplPath, 'common', 'extend', 'package.json')), ffApp)));
                                                    ~~
src/index.ts:61:45 - error TS2532: Object is possibly 'undefined'.

61     const packageJson: Package = JSON.parse(fs.read(packagePath));
                                               ~~
src/index.ts:69:35 - error TS2339: Property 'startFile' does not exist on type 'FioriApp'.

69             startFile: data?.app?.startFile,
                                     ~~~~~~~~~
src/index.ts:70:40 - error TS2339: Property 'localStartFile' does not exist on type 'FioriApp'.

70             localStartFile: data?.app?.localStartFile
                                          ~~~~~~~~~~~~~~
src/index.ts:74:5 - error TS2532: Object is possibly 'undefined'.

74     fs.writeJSON(packagePath, packageJson);
       ~~
src/index.ts:81:5 - error TS2322: Type 'Editor | undefined' is not assignable to type 'Editor'.
  Type 'undefined' is not assignable to type 'Editor'.

81     return fs;
       ~~~~~~~~~~
STACK: 
Failed to collect coverage from C:\git\github\open-ux-tools\packages\fiori-freestyle-writer\src\types.ts
ERROR: src/types.ts:1:29 - error TS2307: Cannot find module '@sap-ux/ui5-application-writer' or its corresponding type declarations.

1 import { Ui5App, App } from '@sap-ux/ui5-application-writer';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/types.ts:2:30 - error TS2307: Cannot find module '@sap-ux/odata-service-writer' or its corresponding type declarations.

2 import { OdataService } from '@sap-ux/odata-service-writer';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/types.ts:45:30 - error TS2307: Cannot find module '@sap-ux/odata-service-writer' or its corresponding type declarations.

45 export { OdataVersion } from '@sap-ux/odata-service-writer';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
STACK: 
------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------|---------|----------|---------|---------|-------------------
All files         |       0 |        0 |       0 |       0 |
 i18n.ts          |       0 |      100 |       0 |       0 | 1-34
 packageConfig.ts |       0 |        0 |       0 |       0 | 1-44
------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        26.919 s
Ran all test suites matching /test\\basic.test.ts/i.
Waiting for the debugger to disconnect...
 ELIFECYCLE  Test failed. See above for more details.
Waiting for the debugger to disconnect...
```

I'm on main branch:

```
C:\git\github\open-ux-tools\packages\fiori-freestyle-writer>git status                      
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Do you have any ideas?

BR
Lukas

**Comment by tobiasqueck** [comment]
@lboehm can you run `pnpm build` and then `pnpm test` in the root folder and check if everything runs without problems?

**Comment by lboehm** [comment]
Hi @tobiasqueck sorry for not being active for so long. But now I've found the time to take a look into this. Here's what I got:

- I'll provide a PR that provides the changes to the productive code. I think / hope the changes are correct. I've verified them by running the tests and inspecting the test output, that is generated when `UX_DEBUG=true` is set.
- I didn't manage to get the tests up and running. I don't have any experience in jest, and I assume I have to generate some more test snapshots. But generating test snapshots somehow didn't work for me. Propably for someone who is used to jest, this shouldn't be a problem. Could you or a colleague take a look at the tests?

Please take a good look into my changes, because in the time I had to invest in this issue, I didn't understand the whole codebase. So I am not 100% sure, that I didn't break things.

BR
Lukas
