### ISSUE TITLE
TBI - Clean separation between prompting and writing in adp-tooling

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#2216]
### Description (include screenshots)
The goal of the separation between the prompting and the writer modules is to be able to use and evolve them separately. Especially when creating complex prompting modules with multiple conditional branches that need to run in the YeomanUI the prompting output will be large flat structures. Such an output can map to one or more writers that need only a subset of the answers. 
To solve that we decided that the general flow is `prompt` -> `transform` -> `write`. The prompting results in usually a flat type named `xyzAnswers` and the writer requires a well structured `xyzConfig`. The mapping between both would happen in the consumer of both prompting and writing. 

The goal of this task is to rework the types and interfaces of https://github.com/SAP/open-ux-tools/tree/main/packages/adp-tooling/src/prompts and their corresponding writers.

### Value
Clean separation of concerns allows better reusability, testability and maintainability. 

### Architecture Elaboration
n/a

### Notes
#2184 was only approved with the agreement that this TBI will be implemented right after.

### Misc
@testojs @mmilko01 

### Tasks
- [ ] add-annotations-to-odata
- [ ] add-new-model
- [ ] change-data-source
- [ ] change-inbound
- [ ] add-component-usage
