### ISSUE TITLE
FEATURE - Publish fiori-tools-proxy modules

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#228]
_As a **tools developer**,
I want to **reuse the proxy functionality that is today only available in the `@sap/ux-ui5-tooling`**,
so that I **can benefit from it in more different setups.**_

### Description
The idea of the feature request is to publish the core functionality of the `fiori-tools-proxy` so that it can be used in other setups as well e.g. using parts of the functionality also in a CAP project. Furthermore, a proxy middleware needs to handle lots of different setups e.g. handle different flavors of corporate proxies, therefore, publishing the sources and allowing developers that have setups in which the `fiori-tools-proxy` doesn't work, to inspect and maybe even contribute to it, will help the overall quality of the proxy.
Lastly, allowing to inspect the sources creates trust into the `fiori-tools-proxy` since a proxy middleware might actually handle sensitive data.

### Technical Design

`@sap-ux/ui5-proxy-middleware`
* an npm module exposing an `express` router that can be used independent of the UI5 CLI but also a configuration to use it as-is with the UI5 CLi
* allow to load UI5 from any http(s) url
* allow selective filtering of what modules are actually loaded from where
* [to-be-evaluated]: allow loading UI5 sources from local folders
* [to-be-evaluated]: exposing advanced settings for the underlying proxy module

`@sap-ux/backend-proxy-middlware`
* an npm module exposing an `express` router that can be used independent of the UI5 CLI but also a configuration to use it as-is with the UI5 CLI
* [to-be-evaluated]: exposing advanced settings for the underlying proxy module

(SAP) `@sap/ux-ui5-tooling`
* include the extracted `express` routers into the `fiori-tools-proxy` and keep the existing API as-is so that there are no disruptions for existing users

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have only the need to proxy UI5 sources
**when** I add the new extracted ui5 proxy module to my project
**then** I can do that by adding it to the ui5.yaml

**Given** I have an issue with `fiori-tools-proxy`
**when** I look at the `open-ux-tools` repository
**then** I can understand exactly how the proxying works.

**Given** I have specific needs for the proxy middleware 
**when** I use and enhance the published proxy modules
**then** I can build my own middleware

### Tasks
- [x] (SAP) Extract the UI5 proxy functionality from the `fiori-tools-proxy` into a new module
- [x] Enhance the extracted UI5 proxy and make it more flexible for known use cases
- [x] (SAP) Extract the backend proxy functionality from the `fiori-tools-proxy` into a new module
- [x] Unit Tests added

**Comment by tobiasqueck** [comment]
Closing it because all sub-tasks are completed.
