### ISSUE TITLE
FEATURE - Generate SAP ABAP annotations in CAP CDS

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#2294]
_As a **developer**,
I want to **generate SAP ABAP annotations**,
so that I **create an ABAP service with basic UI annotations**_

### Description
Add an option to generate SAP ABAP annotations instead of OData annotations from annotation generator as an experimental feature.

### Technical Design
_What modules need to be created or enhanced?_ 
Extend `@sap-ux/fiori-annotation-api` so it can insert SAP ABAP annotations for `LineItem` and `FieldGroup`. (only insert change needs to be supported)
_How would the functionality be exposed and how can it be consumed?_
A `writeSapAnnotations` parameter needs to be passed when creating a new instance of `FioriAnnotationService`.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have fresh CAP project with a UI5 application
**when** I execute generate annotations function with`writeSapAnnotations` parameter
**then** basic SAP annotations for UI will be generated in applications CDS file.

### Tasks
- [x] Implement OData -> SAP ABAP annotation conversion
- [x] Add `writeSapAnnotations` parameter to the `FioriAnnotationService`
- [x] Call conversion in CDS adapter before passing the `insert` change to the writer
- [x] Error handling (currently only limited scope needs to be supported and if the API is called outside the bounds of this scope we'll throw an error)
- [x] Unit Tests added
