### ISSUE TITLE
TBI - Extract XML writer from fiori-annotation-api to a separate package

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#2640]
### Description (include screenshots)
In `@sap-ux/fe-fpm-writer` we need to update XML file content. Currently `@xmldom/xmldom` package is used, which is not aware of the existing formatting and just replaces the whole document, but that is not always desired. In `@sap-ux/fiori-annotation-api` we have an XML writer class which can do more fine grained changes and only update the required parts of the document. We should extract it into a separate package dedicated to writing into XML files, so it can be reused in other modules.

### Value
Ability to reuse formatting and comment preserving XML writing APIs across tools.

### Notes
XML writer https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-annotation-api/src/xml/writer.ts
XML converter https://github.com/SAP/open-ux-tools/blob/main/packages/xml-odata-annotation-converter/src/printer/csdl-to-xml.ts

### Tasks
- [ ] Create a new package  (proposed name `@sap-ux/xml-writer`)
- [ ] Extract writer logic (change -> TextEdit)
- [ ] Extract converter logic (AST -> text)
- [ ] Refactor to remove the dependency to `@sap-ux/odata-annotation-core-types`
- [ ] Use the new package in `@sap-ux/fe-fpm-writer`
