### ISSUE TITLE
FEATURE - Common tree dropdown component based on latest ux/design

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#2682]
### Description

Our current Dropdown Tree shows tree children as separate callout:
![image](https://github.com/user-attachments/assets/b21478b6-1061-4456-a0f2-eea016933f3e)

Latest ux/design is that children is displayed within same callout:
![image](https://github.com/user-attachments/assets/b33937a9-af9e-4f99-90c1-33230be0a8b2)
![image](https://github.com/user-attachments/assets/236ef00e-8a12-4c63-8c3b-f01e3a2c2534)

### Technical Design
New component for tree dropdown.
Additional property to allow select parents/expandable nodes.

### Tasks
- [ ] New component for dropdown tree
- [ ] Property to switch between two modes:
- [ ] Mode to set parent as selectable and expandable/collapsable;
- [ ] Mode to set parent as expandable/collapsable and unselectable;
- [ ] ToDo

@gpeuc
