### ISSUE TITLE
TBI - Clean up eslint warnings in generated projects

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#270]
### Description (include screenshots)
Improve quality of the generated projects. Add missing JSDoc and fix eslint warnings/errors on each floorplan.
Follow on from #254

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [x] Add test for each floor plan with eslint and code assist enabled.
- [ ] Add missing JSDocs
- [ ] Fix eslint issues.

FYI @tobiasqueck

**Comment by tobiasqueck** [comment]
@devinea any updates on this one?

**Comment by tobiasqueck** [comment]
@devinea same question as in February :)

**Comment by devinea** [comment]
@IainSAP You took this over and merged the PR. Is there anything remaining?
