### ISSUE TITLE
FEATURE - Provide modules for project constants and project access

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/open-ux-tools#293]
_As a **developer**, I want to **have API access to SAP Fiori projects**, so that I **can read and update project resources**_

### Description
Multiple tools and modules require functionality to 
- find SAP Fiori projects in a folder/workspace
- access project resources, such as the AppDescriptor (`manifest.json`), local annotations, etc. 

There should be a module that provides a common way to find projects and access resources of them programmatically. Constants and types should also be available as typescript module, which can be same as the module that provides access to a project, or provided as separate module.

### Technical Design
Create module(s) for project types and constants and access to project resources. Other tools or apps can add these modules as dependencies and use exposed functionality.

### Acceptance Criteria
I have a workspace and execute search using the new project access module then the modules returns me a list of SAP Fiori projects and allows accessing resources of them.

### Tasks
- [x] Add module for project constants and project access 
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by Klaus-Keller** [comment]
Published: https://www.npmjs.com/package/@sap-ux/project-access
Closing this ticket.
