### ISSUE TITLE
TBI - Remove ui5 version from ui5.yaml and ui5-mock.yaml files

### ISSUE THREAD

**Issue by unseen1980** [SAP/open-ux-tools#333]
### Description 
It has been agreed that the middleware should determine the version of ui5 in the generated or migrated Fiori app and it no longer needs to be specified in the `ui5.yaml` and `ui5-mock.yaml` files.

### Acceptance criteria

**Before:**

```
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
          version: 1.96.1
```

**After:**

```
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
```

### Tasks
- [ ] Remove version from ui5-config
- [ ] Update TS types
- [ ] Update tests/snapshots
