### ISSUE TITLE
FEATURE - UI5 CDN URL to be `https://ui5.sap.com` by default

### ISSUE THREAD

**Issue by petermuessig** [SAP/open-ux-tools#381]
As a UI5 architect 😁 ,
I want to ensure that all SAP Fiori elements and SAPUI5 freestyle applications are referring to `https://ui5.sap.com` as CDN URL,
so that I can be independent from an SAP platform specific hosting solution like `hana.ondemand.com`.

### Description

We - UI5 - clarified with all major platforms to allow the domain `https://ui5.sap.com` to be a safe host in the CSP settings (`script-src`). Only in some special cases in which developers define an inline CSP `META` tag  it may be possible that the CSP settings prevent consuming UI5 from `https://ui5.sap.com`. In those cases, the developers must adopt their application (`index.html`).

Please also check for the existence of `META`tags:

```
<meta http-equiv="Content-Security-Policy" content="script-src https://sapui5.hana.ondemand.com 'self' ...">
```

Or similar - and also adopt the URL in such `META` tags.

* CSP docu: https://ui5.sap.com/#/topic/fe1a6dba940e479fb7c3bc753f92b28c
* CSP compliance: https://ui5.sap.com/#/topic/1f81a093a9f3433983dcb2ebe11cd4cd

### Technical Design

For all templates in Open UX Tools, please switch the UI5 CDN URL from `https://sapui5.hana.ondemand.com` to `https://ui5.sap.com`. For OpenUI5 we also consider a change - but I will inform you separately about this.

### Acceptance Criteria

**Given** I will create a new SAP Fiori elements or SAPUI5 application
**when** I use the Open UX Tools
**then** I expect that the CDN URL for SAPUI5 points to `https://ui5.sap.com`.

### Tasks
- [x] scan the code for all occurrences sapui5.hana.ondemand.com and replace them
- [x] update required test snapshots
- [x] verify that all builds and tests run smoothly

**Comment by tobiasqueck** [comment]
@petermuessig no productive code contains the old url anymore. It is only used in a test case where the caller provides a custom url which I wouldn't consider a problem.
