### ISSUE TITLE
FEATURE - ui5-application-writer/fiori-elements-writer/fiori-freestyle-writer: Allow absolute UI5 lib urls

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#404]
### Description

Currently when generating apps using @sap-ux/fiori-freestyle-writer or @sap-ux/fiori-elements-writer the generated `index.html` and `flpSandbox.html` files contain relative references to ui5 libraries. These require handling by a middleware proxy to properly resolve. In some instances the middleware proxy will not be installed (apps generated in CAP projects) and so an option to generate with absolute URLs should be possible also.

### Technical Design
The following modules will be updated to support the requirement:
`@sap-ux/ui5-applicaiton-writer` : Add an option to use full ui5 core lib refs for the `src` attribute of the `sap-ui-bootstrap` of the script tag in `index.html`
`@sap-ux/fiori-elements-writer` & `@sap-ux/fiori-freestyle-writer`: Add an option to use full ui5 core lib refs for the `src` attribute of the `sap-ui-bootstrap` of the script tag in `flpSandbox.html`

### Acceptance Criteria

**Given** I am generating a Fiori elements app
**when** I pass the option to use a full url in html files
**then** A full url will be output in those files

### Tasks
- [ ] Update ui5-application-writer to support
- [ ] Update fiori-elements-writer to support
- [ ] Update fiori-freestyle-writer to support
- [ ] Unit Tests added
- [ ] Test Cases defined
