### ISSUE TITLE
TBI - Consolidate types between `ui5-config` and `ui5-proxy-middleware`

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#423]
### Description (include screenshots)
Both modules work with `ui5.yaml` files and thereby defined their own types. The `ui5-proxy-middleware` is mostly not directly accessing the yamls but gets the config as input, however, it is also reading the location of the `webapp` folder from the `ui5.yaml`. 

As result, I suggest to
- move all generic types related to the `ui5.yaml` and the `manifest.json` into the `ui5-config` project
- enhance the `ui5-config` module with functionality to get/set the configuration `/resources/configuration`
- add `ui5-config` as dependency to `ui5-proxy-middleware` and 
   - use the new `getConfiguration` function to get the `webapp` folder
   - use the moved types 

### Value
Consolidated types and removal of duplicated coding. Especially, moving the `manifest.ts` also into the `ui5-config` is useful for all other writers and will further reduce the amount of duplicated types, e.g. #422.

### Architecture Elaboration
Input required from
@zdravko-georgiev  as creator of `ui5-proxy-middleware`
@ullasholla as creator of `ui5-config`

### Tasks
- [ ] move all generic types related to the `ui5.yaml` and the `manifest.json` into the `ui5-config`
- [ ] enhance the `ui5-config` module with functionality to get/set the configuration `/resources/configuration`
- [ ] use `ui5-config` in `ui5-proxy-middleware

**Comment by ullasholla** [comment]
Having common types makes a lot of sense. 
The `ui5-config` module has so far been used by the writers (its name does not make that very clear). It takes care of returning 'configuration' objects (with defaults) that are used when projects are getting created. It does not have much code but does it still make sense to have a dependency to it from `ui5-proxy-middleware`. I guess my question is that context of the config module has been more 'design-time' or 'generation-time' and the proxy middleware is 'runtime'. Does it make sense to draw that distinction at all?

**Comment by tobiasqueck** [comment]
@ullasholla while the  `ui5-config` has only been used by the writers so far, I don't think it should be limited to them. The module was designed to simplify access to UI5 configurations.
The decision about the dependency, I would leave to @zdravko-georgiev . Independent of the dependency, moving the types and then adding it as `devDependency` would still be an improvement allowing to reduce duplications.

**Comment by zdravko-georgiev** [comment]
I would not differentiate between `design-time`, `generation-time` and `runtime`. I like the idea of having a central package with common types and common functions for reading/writing information in/out of the project. This has proven to be very useful.
