### ISSUE TITLE
FEATURE - Support custom views in list reports

### ISSUE THREAD

**Issue by stefanschreck** [SAP/open-ux-tools#462]
_As a **developer**,
I want to **use the FPM writer to create a custom view in list report**,
so that I **define custom views for the multiple views' scenario**_

### Description

When I compare the capabilities of the FPM writer with the documentation of the FPM explorer I can find a gap: the custom views in list report are not supported, as described [here](https://sapui5untested.int.sap.eu2.hana.ondemand.com/test-resources/sap/fe/core/fpmExplorer/index.html#/customElements/customElementsOverview/customViewInLRContent).

We invested a lot over the last weeks in supporting ALP views and LR multiple views in the Application Modeler of the Fiori Tools suite, and detected the custom views as the last missing feature here. Thus is would be great to add the functionality to create new custom views at the FPM writer, similar to other existing API functions.

### Technical Design
Following the examples at the [FPM explorer ](https://sapui5untested.int.sap.eu2.hana.ondemand.com/test-resources/sap/fe/core/fpmExplorer/index.html#/customElements/customElementsOverview/customViewInLRContent) the new API function `createCustomView` shall 
- create a new fragment, following a template (note: the FPM explorer shows two examples, a table and a panel with a button, but I guess the table is - besides a chart - the most common use case; thus I'd like to propose to present a simple view template, plus an option to have a table as content).
- the new fragment shall be registered in manifest as a new view.
- create an event handler if required (optional parameter); if specified, the API shall also create the extends.extensions entry in manifest for this controller.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I want to add a new custom view to a list of multiple views at the FE list report
**when** I call the new API
**then** a view and (optionally) a controller gets created and the new view is added to the views section at the manifest; in a preview can see the additional view.

### Tasks
- [x] Create view
- [x] Create controller
- [x] Update views in manifest
- [x] Update extension in manifest
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by tobiasqueck** [comment]
@stefanschreck could you please rework the acceptance criteria and be more specific and what use case we need to cover?

**Comment by tobiasqueck** [comment]
Are there other places e.g. in an object page where we could add a custom view? Would it make sense to design the API more flexible?

**Comment by stefanschreck** [comment]
> Are there other places e.g. in an object page where we could add a custom view? Would it make sense to design the API more flexible?
@tobiasqueck 
Answer is no. It's about multiple views' scenario which only is supported on LR.

**Comment by stefanschreck** [comment]
> @stefanschreck could you please rework the acceptance criteria and be more specific and what use case we need to cover?

@tobiasqueck reworked.

**Comment by tobiasqueck** [comment]
@stefanschreck can we close this one since #525 has been merged?

**Comment by stefanschreck** [comment]
Can be closed
