### ISSUE TITLE
FEATURE - Add abstraction for LREP service to `axios-extension`

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#468]
_As a **developer of tools**,
I want to **build a command line tool interacting with the LREP service**,
so that I **deploy adaptation projects**_.

### Description
The `axios-extension` module already nicely abstracts SAP OData services that are commonly used in tools to build applications. To be able to also provide a similar tooling for working with adaptation projects, and abstraction of the layer repository (LREP) service is required.

### Technical Design
`axios-extension`: a new service with convenience functions for lrep needs to be added (no other change required)

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a zipped adaptation project
**when** I can write and execute a simple script without detailed knowledge about the LREP service
**then** my adaptation project is deployed.

### Tasks
- [x] Create and implement service abstraction
- [x] Unit Tests added
- [x] Test Cases defined
