### ISSUE TITLE
FEATURE - Add support for `sourceTemplate.toolsId` manifest.json property

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#480]
### Description

Since ui5 app descriptor version 42 and new `sap.app.sourceTemplate` property `toolsId` has been added to allow template tools to include a tracking id. See: https://ui5.sap.com/#/topic/be0cf40f61184b358b5faedaec98b2da

This feature will allow this value to be set and included in the generated ui5 applications.

### Technical Design
This requires the addition of the new property to the relevant type and template. Since this is an optional property it should not write a default value if the value is not provided.

### Acceptance Criteria
When a UI5 app is generated, providing the a value for the `toolsId` property, the value will be correctly present in the generated apps `manifest.json` file

### Tasks
- [ ] Update type definitions to include an optional `toolsId` property
- [ ] Unit Tests added
- [ ] Test Cases defined
