### ISSUE TITLE
TBI - Use Typescript Project References for build better performance

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#495]
### Description (include screenshots)
Use Typescript Project References for better performance in the build.
https://www.typescriptlang.org/docs/handbook/project-references.html

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Generate TS project references in the tsconfig.json files base on pnpm workspace dependencies
- [ ] Add script/hook to auto update the TS project references
- [ ] Add `compilerOptions` to tsconfig.json
 ```
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "incremental": true,
    "outDir": "dist",
    "rootDir": "./src",
```
- [ ] Change build/watch scripts to use `--build` instead of `--project` for `tsc` cli.
- [ ] Update ignore files to ignore `*.tsbuildinfo`
- [ ] Adjust tsconfig include/exclude as needed based on `rootDir` setting
- [ ] As necessary add a tsconfig file for tests files and configure jest/eslint etc.. to use it.
- [ ] Bench mark the performance changes.

**Comment by devinea** [comment]
This would likely not add much benefit now that NX has been implemented on the build.
Closing
