### ISSUE TITLE
FEATURE - Provide modules for reading and writing annotations

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-tools#506]
_As a **developer**,
I want to **have API access to annotations in SAP Fiori elements projects**,
so that I **can read and write annotations programatically**_

### Description

Multiple tools require functionality to read and write annotations in order to assist users in developing SAP Fiori elements applications. There should be a module that provide a common way of interacting with annotations in SAP Fiori elements projects. It should support annotations defined in XML and [SAP CAP CDS](https://cap.cloud.sap/docs/cds/cdl#annotations) files.

### Technical Design
Create module(s) that facilitate reading and writing annotations in SAP Fiori elements projects. Other tools or apps can add these modules as dependencies and use the exposed functionality.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a SAP Fiori elements project
**when** I execute `getSchema` function 
**then** I will get all of the defined annotations in `RawMetadata` format defined by `@sap-ux/vocabularies-types`.

**Given** I have a SAP Fiori elements project
**when** I execute `edit` function 
**then** The change will be added to the change stack, which later can be saved to a file.

**Given** I have a SAP Fiori elements project
**when** I execute `save` function 
  **and** I have made changes to annotations
**then**  my changes will be saved in annotation file(s).

### Tasks
  - [x] @sap-ux/odata-annotation-core-types 
  - [x] @sap-ux/odata-annotation-core 
  - [x] @sap-ux/odata-entity-model 
  - [x] @sap-ux/odata-vocabularies 
  - [x] @sap-ux/xml-odata-annotation-converter 
  - [x] @sap-ux/cds-annotation-parser 
  - [x] @sap-ux/cds-odata-annotation-converter 
  - [x] @sap-ux/fiori-annotation-api
  - [x]  @sap-ux/annotation-generator
