### ISSUE TITLE
FEATURE - `axios-extension` enhancement requests

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#634]
This is a collection of small enhancement requests for the `axios-extensions` received through private channels by consumers. 

_As a **consumer of the `axios-extension`**,
I want to **be able to inspect the axios errors when using the catalog service**,
so that I **can better analyze why something went wrong.**_

_As a **consumer of the `axios-extension`**,
I want to **be able to use service aliases for all main service implementations**,
so that I **can also use it with backends that block the standard service urls.**_

### Description

These enhancement requests, while received for specific scenarios, are valid for a broader range of scenarios that will also be required by other consumers including the SAP Fiori tools.

### Technical Design
All changes will be in the `axios-extension` module. The alias handling should mainly require to change the service factory functions. Exposing the error object will require changes to the catalog service, however, it makes sense to also check other convenience functions in our services.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I call the catalog service (v2 or v4)
**when** there is an error
**then** I will have access to the low-lever axios error object

**Given** I have a service not available at the default path but an alias
**when** when I call it
**then** I can provide the alias but still have full access to the convenience functions

### Notes
fyi @Klaus-Keller @cianmSAP 

### Tasks
- [ ] expose error objects
- [ ] enhance interface for aliases
- [ ] Unit Tests added

**Comment by Klaus-Keller** [comment]
@tobiasqueck, with https://github.com/SAP/open-ux-tools/pull/830 we implemented  access to the full axios error object in `@sap-ux/environment-check`. There were no changes required in `axios-extension` and I propose to close this ticket.
