### ISSUE TITLE
FEATURE - enable typescript in an existing project

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#666]
_As a **developer**,
I want to **enable typescript support in an existing JS project**,
so that I **also write modern code.**_

_As a **consumer of the the open-ux-tools**,
I want to **be able check if a project has typescript enabled**,
so that I **can offer additional functionality**_

### Description

This is a follow up to #621

The `ui5-application-writer` needs to be extended to offer functionality allowing to check if an existing project has `typescript` enabled and needs to allow to enable it for existing projects

### Technical Design
Typescript is enabled if the `ui5.yaml` files have the correct middlewares configured, therefore, the `ui5-config` module needs to be enhanced to allow checking for specific tasks or middlewares and then this functionality needs to be consumed by the `ui5-application-writer` and an `isTypescriptEnabled` as well as `enableTypescript` function needs to be exposed.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a valid UI5 project
**when** I execute `isTypescriptEnabled` 
**then** I will know whether the project supports typescript coding or not.

**Given** I have I have UI5 project that doesn't support typescript yet
**when** I execute `enableTypescript`
**then** I will be able to start using typescript in my project

### Tasks
- [x] enhance `ui5-config`
- [x] enhance `ui5-application-writer`
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by tobiasqueck** [comment]
Implemented with #667
