### ISSUE TITLE
FEATURE - Publish deploy-to-abap task from the @sap/ux-ui5-tooling module

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#687]
_As a **tools developer**,
I want to **reuse the deployment task that is today only available in the `@sap/ux-ui5-tooling`**,
so that I **can benefit from it in more different setups**_

### Description
The idea of the feature request is to publish the deployment functionality of the `deploy-to-abap` task (https://www.npmjs.com/package/@sap/ux-ui5-tooling#deployment-to-abap) so that it can be used in other setups as well e.g. standalone in a CI/CD setup. 
Furthermore, the task needs to handle lots of different setups e.g. handle different flavors of corporate proxies, therefore, publishing the sources and allowing developers that have setups in which the `@sap/ux-ui5-tooling` doesn't work, to inspect and maybe even contribute to it, will help the overall quality of the task.

### Technical Design
New module `@sap-ux/abap-deploy-task`
* configurable as UI5 custom task
* deploy functionality can also be called programmatically independent of the ui5 tooling
* simple CLI exposed so that it can also be called directly in a terminal

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

Given I have only the need to deploy to an ABAP system
when I add the new extracted ui5 task module to my project
then I can do that by adding it to the ui5.yaml

Given I have an issue with deploy-to-abap task
when I look at the open-ux-tools repository
then I can understand exactly how the deployment works.

Given I have specific needs for the deploy-to-abap task
when I use and enhance the published module
then I can build my own deployment module

### Tasks
- [x] create new module
- [x] Unit Tests added
- [ ] Test Cases defined

**Comment by longieirl** [comment]
Issue found when further testing
https://github.com/SAP/open-ux-tools/issues/989

**Comment by tobiasqueck** [comment]
The requested functionality has been added and integrated back into the Fiori tools
