### ISSUE TITLE
FEATURE - EnvCheck - Enable environment check for VSCode

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#694]
**As a developer developing Fiori application using SAP Fiori tools in VSCode, I would like a quick better way to gather basic information about my environment so that I can send it to SAP while reporting incident to minimize the time it takes going back n forth to support asks about installed component versions**

### Description

- SAP Fiori tools Environment Check for SBAS has been beneficial for reducing the support roundtrip and is being used by SAP Fiori tools team as well as SBAS support team and slowly growing.
- Now, with this US, we want to introduce first set of a similar environment check tailored towards VSCode which will help both internally and externally with customers who are running into issues related to running SAP Fiori tools in VSCode.
- This feature will help Fiori tools team to gather most relevant info. Of course, this is initial set, can be expanded later. 
- We will have follow up US to have saved `SAP systems check`, similar to what we do for destination in SBAS
- If during grooming, team is ok, then we can enable similar for SBAS too.

Environment Check in VSCode will report/check the following:
1. node version
2. Cloud CLI tools installed or not
3. Application Wizard version
4. SAP Fiori tools - Application generator version
5. SAP Fiori tools - Application Modeler version
6. SAP Fiori tools - Guided Development version
7. SAP Fiori tools - Service Modeler version
8. SAP Fiori tools - XML Annotation Language Server version
9. XML Toolkit version
10. SAP CDS Language Support version for CAP
11. UI5 Language Assistant Support extension

### Design
Interaction
Functional Flow 1
- User in VSCOde enter command `Fiori: Open Environment Check`
- From the quick pick, user selects `Gather environment information`
- A `envirnoment_info.md` file opens with title `SAP Fiori tools - Environment Details` and is saved under `envcheck-<timestamp>.zip`

### Acceptance Criteria
- Given i run command `Fiori: Open Environment Check` and select `Gather environment information`, I should be shown environment info in a .md file and should also be saved in a zip file.

Sample Output:

| Tools/Extensions                                 | Version |
|--------------------------------------------------|---------|
| Node.js                                          |         |
| Cloud CLI tools                                  |         |
| Application Wizard                               |         |
| SAP Fiori tools - Fiori generator                |         |
| SAP Fiori tools - Application Modeler            |         |
| SAP Fiori tools - Guided Development             |         |
| SAP Fiori tools - Service Modeler                |         |
| SAP Fiori tools - XML Annotation Language Server |         |
| XML Toolkit                                      |         |
| SAP CDS Language Support                         |         |
| UI5 Language Assistant Support                   |         |

### Notes

--- 

### Tasks
- [ ] Add relevant checks for VSCode env check
- [ ] Unit Tests added
- [ ] Test Cases defined 
- [ ] Optional - UI Automation Tests added

**Comment by tobiasqueck** [comment]
@cianmSAP can this be closed? It was implemented with #695.

**Comment by cianmSAP** [comment]
Implemented with https://github.com/SAP/open-ux-tools/pull/695.
