### ISSUE TITLE
CHORE - Improving code quality

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#697]
### Description (include screenshots)
* enable linting also for test folders
* review and improve pre-commit scripts to ensure consistent outputs
* drastically reduce the amount of warning we get when running `pnpm lint`

### Value
The goal is to have no lint warnings in our `open-ux-tools` project. If code with warnings is pushed to main then only as a temporary state, the expectation is that the warnings are to be fixed. If an error or warning is to be permanently accepted - which should only happen in exceptional cases - then eslint-disable-next-line can be used and it is expected that the reviewer has a close look at it, and by approving also takes co-accountability for the disabled rule.

### Notes
It is not required to get the number to zero with this issue BUT close to it, and every remaining warning needs to be acknowledge in some way or another.

### Tasks
- [ ] Review and improve pre-commit scripts to ensure consistent outputs (#701)
- [ ] axios-extension
- [ ] environment-check
- [x] fe-fpm-writer (#699)
- [ ] fiori-elements-writer
- [ ] fiori-freestyle-writer
- [ ] logger
- [x] odata-service-writer (#702)
- [ ] store
- [x] ui-components (#700)
- [x] ui5-application-writer (#702)
- [ ] ui5-config
- [ ] ui5-proxy-middleware
- [x] yaml (#709)
