### ISSUE TITLE
FEATURE - Use ADT service to create transport request

### ISSUE THREAD

**Issue by slin-sap** [SAP/open-ux-tools#711]
### Description

As the consumer of axios-extension AbapServiceProvider, SAP Fiori tools - Deployment config generator is planing to support a new feature, which allows its users to create a new transport request and use the new transport request in the generated configuration.

### Technical Design

axios-extension: Need to add createTransportRequest implementation to AbapServiceProvider. Expose this implementation from ServiceProvider to be consumed by UX tools suite Deployment config generator.

### Acceptance Criteria

**Given** consumer needs to create a new transport request
**when** the new createTransportRequest is called with input parameter description: string.
**then** ADT service for creating transport request should be executed and ABAP backend should return the newly created transport request ID.

### Tasks
- [x] PoC to test ADT service
- [x] Implement createTransportRequest and expose interface to axios-extension consumer
- [x] Unit Tests added

**Comment by slin-sap** [comment]
This issue depends on previous PR: https://github.com/SAP/open-ux-tools/pull/627

**Comment by tobiasqueck** [comment]
Finished with #793
