### ISSUE TITLE
FEATURE - Publish Fiori elements templates

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#72]
_As a **developer of tools**,
I want to **be able to reuse the Fiori elements templates**,
so that I **can build tools that generate state of the art projects.**_

### Description
The FIori elements templates are currently part of the application generator and cannot be reused by external tools developers e.g. as part of the `easyUI5` project. By publishing the templates, we enable these other projects to also generate Fiori elements projects while ensuring the correctness of the generated files.
Furthermore, by publishing the templates we empower the community to improve the existing templates.

### Technical Design
- encapsulate templates into a template module with a well defined interface exposing a method to generate a Fiori elements project
- ensuring that common files are not duplicated within the template 

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have tools project 
**when** I want to add the generation of Fiori elements projects
**then** I can easily integrate the Fiori elements templates

**Given** I have integrated the Fiori elements templates
**when** I call in my tools with the required input
**then** I can be assured that the generated project is a valid Fiori elements project

### Tasks
- [x] Extract code from the Fiori tools
- [x] remove duplicates
- [x] validate with Fiori elements experts that the templates are up-to-date
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by IainSAP** [comment]
Closing as completed.
