### ISSUE TITLE
FEATURE - CLI to enhance Fiori elements for OData v4 projects with the flexible programming model

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#73]
_As a **developer**,
I want to **be able to efficiently add flexible programming model extensions** to my Fiori elements for OData v4 application,
so that I can **focus on the actually functionality** instead of integration syntax._

### Description
A developer using the flexible programming model is likely to be a technical person that is familiar with (or even fond of) the CLI to generate project artifacts. With this feature we want to empower those developers to efficiently add FPM extensions like custom pages or custom actions to their projects. 
In addition, the more UI based tools (Fiori tools page modeler and guide development) can also make use of the templates and prompts used by the CLI, so that FPM extensions generated with the CLI or other tools are consistent.

### Technical Design
* separate the functionality into three modules
  * templates: containing all templating logic and exposing functions for each available FPM extension e.g. page, section, action etc.
  * prompts: generic definition of prompts that can be used by the CLI but also by UI based tools
  * cli: create a module that can be executed with `npm init` without the requirement to install anything like `yo` etc. (https://docs.npmjs.com/cli/v7/commands/npm-init) 
* templates and prompts have are to be isolated
* cli will depend on templates and prompts and transform output from prompts to the required input for the template
* other tools should use templates and prompts as needed but should not require the cli module

### Acceptance Criteria
**Given** I am in the root folder of an existing Fiori elements v4 project
**when** I execute `npm init @sap-ux/fiori-fpm`
**then** I will be able to use a simple CLI based generator adding FPM boilerplate code to my project.

**Given** I am NOT in the root folder of an existing Fiori elements v4 project
**when** I execute `npm init @sap-ux/fiori-fpm`
**then** I will be told what I did wrong.

**Given** I am the developer of tools for Fiori elements
**when** I want to reuse either the templates or the prompts
**then** I will be able to do that without any other unnecessary modules.

### Tasks
- [ ] validate with Fiori tools page modeler and guided development experts that the exposed modules are reusable for them
- [ ] create template module
- [ ] create prompts module
- [ ] create cli module using templates and prompts
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by tobiasqueck** [comment]
Current state:

- custom page, action and column have been released as `@sap-ux/fe-fpm-writer`
- Fiori tools team is working on replacing the existing custom page implementation with the `@sap-ux/fe-fpm-writer`
- Fiori tools team is working on adding custom columns using the `@sap-ux/fe-fpm-writer`

No code duplications and first set of FPM features is transparently implemented in the `open-ux-tools` repository.
