### ISSUE TITLE
FEATURE - Enable TS support for SAPUI5 application

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#746]
**As a Fiori developer using the basic SAPUI5 template in the Fiori generator, I'd like the option to generate the project with TypeScript support.**

### Description

With the delivery of `@sap/generator-fiori#21585` (internal issue), TypeScript is now an advanced option during generation. In order to support TechEd workshops, we need to enable this TypeScript option for the SAPUI5 Basic template only.

This is a requirement for the TechEd workshops, demonstrating Typescript support inside Fiori Freestyle applications.

### Technical Design
Core changes to `ui5_application_writer` and should only impact Fiori Freestyle writer, all other writers should not be affected.

The generated package.json for the Fiori Freestyle application should support typescipt build step for both the `npm run start` and `npm run build` commands.

### Acceptance Criteria
Given I launch the generator and choose the `Freestyle` -> `SAPUI5 Application` as the template
when the Fiori App is generated
then the application will support Typescript 

Given I have a Freestyle application
when  I run the Freestyle `start` and `build` commands
then Typescript command should also be executed but only for SAPUI5 template

Given I have a Freestyle application that is dependent on npmjs modules `@sapui5/ts-types-esm` and `@sapui5/ts-types`
when  the minimium UI5 version is specified
then the install phase should install versions that are available on npmjs and should not fail the install phase

### Tasks
Required
- [x] Ensure`ts-typecheck` is run as part of `npm run start` and `npm run build` steps, restricted only for Basic SAPUI5 template
- [x] Validate all npm modules added to `package.json` are available on npm.js for both `@sapui5/ts-types-esm` and `@sapui5/ts-types` otherwise the Fiori app install will fail 
- [x] Unit Tests

Nice to have
- [ ] Include fallbacks for offline usage so if user is restricted from accessing npmjs, the generation should not fail

**Comment by longieirl** [comment]
There is a change in the behaviour, if a user selects TS and code assist during the project generation flow, then the types version specified for both will be aligned, using the [ESM types version](https://www.npmjs.com/package/@sapui5/ts-types-esm) as the min version. However, if a user generates a SAPUI5 app with only code assist, then the types min version will be from [@sapui5/ts-types](https://www.npmjs.com/package/@sapui5/ts-types)
