### ISSUE TITLE
TBI - Extract and modularize the `odata-client` library from the Fiori tools and publish it

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#75]
### Description (include screenshots)
The `odata-client` is a module that is reused by many other released modules of the Fiori tools e.g. the application generator or the deployment tooling. The module abstracts and simplifies accessing an OData service (v2 and v4) in a node application. In addition, it also allows access to a secure storage as well as implementing different authentication mechanisms.
The goal of this TBI is to expose this functionality to others as well that want to build tools around OData based SAP applications. While moving it into the public space, it is required to revisit its structure allowing consumers to only use the needed functionality e.g. secure storage access or odata request abstraction instead of always requiring the full module with all its dependencies.

### Value
- other tools can utilize the odata-client functionality which is required when prompting and validating the input for integrating an odata service into a project
  - prerequisite for publishing the prompting for Fiori elements application generators
- more modular structure simplifies the integration into other modules
- improved maintainability due to the more modular structure 

### Architecture Elaboration
To be discussed with @ullasholla 
Thoughts:
- the odata-client contains three different functionalities:
  - client: abstraction of odata requests
  - connection: connection handling in SAP Business Application Studio or VSCode, with basic auth or OAuth (and SAML)
  - systems: managing systems and credentials allowing them to be reused for different projects
- all three should be in separate modules, ideally independent of each other, so that the integrating module can pick and choose

### Tasks
- [x] (internal): extract `odata-client` from Fiori tools mono repo
- [x] (internal): remove test/sample coding containing SAP internal information
- [x] create branch(es) with skeleton draft of required modules
- [ ] review (& refactor if needed) all functionality required for client/connection handling
- [x] review (& refactor if needed) all functionality required for storing and using credentials
