### ISSUE TITLE
TBI - Better way to handle Typescript commands across all template types

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#754]
### Description (include screenshots)
As part of the changes introduced by [TBI 746](https://github.com/SAP/open-ux-tools/issues/746), there needs to be further changes made. The changes introduced were to support the basic template only. TS support and what was introduced in for the Simple template needs to support all template types.

- remove conditional code added in this PR https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/src/packageConfig.ts#L66
- enhance the template in ui5-application-writer to support adding TS commands
- validate and fix all provided ts templates in fiori-*-writer to not throw errors when running a typecheck

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Notes
There have been issues with other template types and Typescipt which is why the change was restricted to Simple only.

### Tasks
- [x] Remove conditional code added in this PR https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/src/packageConfig.ts#L66
- [x] Enhance the template in ui5-application-writer to support adding TS commands
- [x] Validate and fix all provided ts templates in fiori-*-writer to not throw errors when running a typecheck  https://github.com/SAP/open-ux-tools/pull/845

**Comment by devinea** [comment]
Closing. As tasks where completed
