### ISSUE TITLE
FEATURE - Enhance Fiori freestyle API for integration into `easy-ui5`

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#78]
_As a **developer**,
I want to **generate Fiori freestyle project with more flexibility**,
so that I **can choose my own view names or select the source of UI5**_

### Description
When @vobu tried integrating the `fiori-freestyle` template into the `easy-ui5` following features were not possible to be set:

1. Configure a custom view/controller name instead of the currently hardcoded name
2. Configure the target url that is used to load UI5 in the preview
3. Generate a project using OpenUI5 instead of SAPUI5.

### Technical Design
Coming up with a technical design that works with both `@sap/generator-fiori` as well as with `easy-ui5` needs to be evaluated.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I am using `easy-ui5`
**when** I execute the newly integrated `fiori-freestyle` templates
**then** I will be able to define my custom view name.

**Given** I am using `easy-ui5`
**when** I execute the newly integrated `fiori-freestyle` templates
**then** I will be able to use OpenUI5 loaded from a custom location.

**Given** I am using `@sap/generator-fiori`
**when** I generate a Fiori freestyle project
**then** I want it to behave as today without requiring me to enter more information.

### Notes
_none_

### Tasks
- [x] Discuss an extension of the API with experts from both `@sap/generator-fiori` as well as with `easy-ui5`
- [x] Implement the agreed API extension 
- [x] Experts from both `@sap/generator-fiori` as well as with `easy-ui5` verify the implementation
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by tobiasqueck** [comment]
@vobu could you please check if I collected all requested changes from #65?

**Comment by vobu** [comment]
> @vobu could you please check if I collected all requested changes from #65?

in principle all good. 
would still word things differently for "Description" > "2."
"Configure a custom bootstrap URL for consuming UI5 runtime resources"
this would also make "3." obsolete IMO.

Acceptance criteria are spot on.

**Comment by tobiasqueck** [comment]
The features described are implemented and the acceptance criteria is fulfilled. 
@vobu did we miss something?

**Comment by vobu** [comment]
just FTR: /me thinks, we're good 👍
