### ISSUE TITLE
FEATURE - Add UI Component to support context sensitive help

### ISSUE THREAD

**Issue by IainSAP** [SAP/open-ux-tools#821]
_As a UI Developer,
I want to show context sensitive help in-situ,
so that I provide contextually relevant help links and actions to users _

### Description

Adds a new UI component that can be used to display help links or trigger callbacks wit specific command configuration for integration to ide environments such as VSCode.

### Technical Design

- Adds new module `UIGuidedAnswersBox`
- Can be configured with url links
- Can be configured with command actions (passed as args to the callback on click) in the format:
- Can be configured with link text
- Can be configured with sub-text
- Can be configured with a  `UIIcon` other than the default provided
- Should re-use existing fluent-ui and/or UI Components to ensure consistent behaviour, look & feel.

Example: 
```
export interface IActionCalloutDetail {
    linkText: string;
    subText: string;
    /**
     * Command to be executed and parameters passed to the command
     */
    command?: {
        id: string;
        params: Object | string;
    };
    /**
     * A http url string, command takes precedence if provided
     */
    url?: string;
}
```

UI Design:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/46536134/205698277-cb0e5a43-1b09-44a6-a32b-2a589f3f96c8.png">

### Acceptance Criteria

Sufficent tests are provided to prove feature requirements.

### Tasks
- [x] Add new component:  `UIGuidedAnswersBox`
- [x] Add to `storybook`
- [x] Add unit tests

**Comment by IainSAP** [comment]
Done
