### ISSUE TITLE
FEATURE - provide stringified results for copying to clipboard

### ISSUE THREAD

**Issue by cianmSAP** [SAP/open-ux-tools#875]
_As a **consumer of environment check**,
I want to **get the results as a string**,
so that I **can copy and paste them for further use**_

### Description
The results can be formatted to a string so a consumer can easily copy and paste them.

### Technical Design
Expose a function which will take in the environment check results and parse them to return a string. The string will contain the environment development information, i.e platform, dev environment & tools/extensions.

### Acceptance Criteria
Given I have retrieved the environment check results, and I run the new function by passing in the results, it will return a stringified version of the results which is suitable for copying to the clipboard.

### Tasks
- [ ] Develop and expose a function `formatResultsForClipboard`
- [ ] Unit Tests added
- [ ] Test Cases defined 

@Klaus-Keller
