### ISSUE TITLE
TBI - Support @ui5/cli v3 in the generated projects

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#904]
### Description (include screenshots)
What will this TBI achieve, and how will it be measured as done. Is it documentation, increase of test coverage, refactoring

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

https://sap.github.io/ui5-tooling/v3/updates/migrate-v3/

### Tasks
- [x] Update package.json dependency to v3
- [x] Update ui5*.yaml template(s)
- [x] revert templates changes in  https://github.com/SAP/open-ux-tools/pull/903 
- [x] revert templates changes in  https://github.com/SAP/open-ux-tools/pull/928

**Comment by docirl** [comment]
@devinea pr with changes for this has been merged, so this tbi should be ok to close.

**Comment by devinea** [comment]
Thanks @docirl
