### ISSUE TITLE
FEATURE - support smartlinks configuration in Fiori apps

### ISSUE THREAD

**Issue by johannes-kolbe** [SAP/open-ux-tools#916]
As a developer,
I want to deliver my application with pre-configured targets for the included smart links,
so that I can create/modify smart link configurations in my changes folder and deliver together with my app.

### Description

This feature request should enable a user to add a smart links configuration to an application. With those pre-configured targets from the system, changes can be done directly and included before deployment.

### Technical Design
- New module `@sap-ux/app-config-writer`
- Include in `@sap-ux/create` module as `add smartlinks-config` command

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an existing application with system configuration in `ui5-deploy.yaml`
**when** I execute `@sap-ux/create add smartlinks-config` command
**then** a smartlinks configuration will be added to the application

**Given** I have an existing application without `ui5-deploy.yaml`
**when** I execute `@sap-ux/create add smartlinks-config` command
**then** I can enter system details and a smartlinks configuration will be added to the application

**Given** I have a smartlinks configuration in the application
**when** I start flp preview
**then** changes can seen with those targets considered.

### Notes
- Under the `webapp/appconfig` folder a `fioriSandboxConfig.json` is created, containing links e.g.:
```
{
  "services": {
    "ClientSideTargetResolution": {
      "adapter": {
        "config": {
          "inbounds": {
            "firstLink": {
              "semanticObject": "SmartLinkNavigation",
              "action": "tofirstlink",
              "title": "Navigate to First Link",
              "signature": {
                "parameters": {},
                "additionalParameters": "allowed"
              },
              "resolutionResult": {}
            },
            ...
          }
        }
      }
    }
  }
}
```

- This is then referenced as custom middleware `fiori-tools-servestatic` in `ui5/ui5-mock/ui5-local.yaml`, e.g.:
```
    ...
    - name: fiori-tools-servestatic
      beforeMiddleware: fiori-tools-proxy
      configuration:
        paths:
          - path: /appconfig
            src: appconfig
```

### Tasks
- [x] Create new module
- [x] Include in `@sap-ux/create`
- [x] Unit Tests added
- [x] Test Cases defined

**Comment by tobiasqueck** [comment]
@johannes-kolbe could you add a little more information about what files will be modified or added, maybe a snippet with an example?

**Comment by johannes-kolbe** [comment]
@tobiasqueck Added more information about the modified files and a snippet of the expected `fioriSandboxConfig.json` and changes to `ui5.yaml`

**Comment by johannes-kolbe** [comment]
@Klaus-Keller For the integration into `@sap-ux/create`, should a possibility to "remove" the smartlinks configuration be available too? The question arises, if yes, what exactly should be removed/modified then..

**Comment by Klaus-Keller** [comment]
@johannes-kolbe, for `@sap-ux/create` it is technically not required to have also a `remove` option. If it does not really make sense, you can skip it. Perhaps align with Christoph.

**Comment by cfg74** [comment]
@johannes-kolbe @Klaus-Keller I would consider a remove as a prio 2 topic at this point, as an existing configuration doesn't influence something negatively. And update option via "add" is available.
