### ISSUE TITLE
FEATURE - Simplify working with /sap/bc/adt/filestore/ui5-bsp service

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-tools#943]
_As a **developer** building tools using the `axios-extension`,
I want to be able to **access ADT filestore service** for UI5 BSP objects `<ABAP-system>/sap/bc/adt/filestore/ui5-bsp`,
so that I **can download artifacts on the fly that are required in my tools**_

### Description
When developing tools for adaptation or extension projects, it is required to access the base application that is to be extended/adapted. For ABAP systems that can be done using the ADT filestore service. By adding this to the `axios-extension` the usage will be consistent with accessing any other backend service in the same process. 

### Technical Design
The `axios-extension` needs to be enhanced to expose another service instance with helper functions for the ADT filestore service.

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have an instance of the AbapServiceProvider (https://github.com/SAP/open-ux-tools/blob/main/packages/axios-extension/src/abap/abap-service-provider.ts)
**when** I call the getter for the AdtFilestoreService
**then** I get an axios instance enhanced with convenience functions

**Given** I have an instance of the AdtFilestoreService
**when** I know the name of a deploy UI5 application
**then** I get the content structure of the deployed archive

**Given** I have an instance of the AdtFilestoreService
**when** I know the name of a deploy UI5 application and an included file
**then** I get the content of the included file

### Notes
Example urls:
* https://abap-system.example/sap/bc/adt/filestore/ui5-bsp/objects/\<app-name\>/content - returns the content structure of the deployed archive
* https://abap-system.example/sap/bc/adt/filestore/ui5-bsp/objects/\<app-name\>/\<file-path-and-name\>/content - returns the content of a specific file

### Tasks
- [ ] Create `AdtFilestoreService`
- [ ] Enhance `AbapServiceProvider` to return this service
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by slin-sap** [comment]
@tobiasqueck I misunderstood the ADT service behavior by looking at the examples. I thought there were 2 services, 1st example url for getting the full archive content structure, and the 2nd example url for getting file content of a given file path.

But when I test the service, it seems there is only one service: https://sap/bc/adt/filestore/ui5-bsp/objects/<file-or-folder-path-and-name>/content 

If a folder path is provided (app-name is treated as root folder), the response is XML data that contains a list of files and folders directly under the folder path provided in the url. It doesn't provided the entire archive content tree structure.

If a file path is provided, the file content text is returned by the service.

Please let me know if it aligns with your expectation.

**Comment by quiggs1001** [comment]
@slin-sap are we ok to close this?  Looks to be implemented in OS.

**Comment by slin-sap** [comment]
> @slin-sap are we ok to close this? Looks to be implemented in OS.

Yes. This GH issue is already implemented.

**Comment by slin-sap** [comment]
Implementation completed and code merged into main branch.
