### ISSUE TITLE
TBI - refactor `locate-reuse-lib.js` template

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#969]
### Description (include screenshots)
What will this TBI achieve, and how will it be measured as done. Is it documentation, increase of test coverage, refactoring

Refactor `locate-reuse-lib.js` template
- Replace deprecated UI5 API's with newer ui5 API's
- Use Async loading for perforance
- Address lint issues

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [x] Replace deprecated UI5 API's with newer ui5 API's
- [x] Use Async loading for performance
- [x] Address lint issues
- [x] update snapshots in tests
- [ ] enable strict mode on `locate-reuse-libs.js`  https://github.com/SAP/open-ux-tools/pull/966#issuecomment-1497916420
- [ ] Remove the rules below
/*eslint-disable fiori-custom/sap-browser-api-warning, fiori-custom/sap-no-dom-access*/

**Comment by heimwege** [comment]
hey guys 👋🏻 

just stumbled across this issue.
`ui5linter` currently complains about the following 26 findings of the current version of `locate-reuse-lib.js` in main:

```
C:\SAPDevelop\git\grl-template-ui\webapp\test\locate-reuse-libs.js
   45:4  error Access of global variable '$' ($.ajax)
  113:23 error Import of deprecated module 'sap/base/util/UriParameters'
  121:13 error Access of global variable '$' ($.ajax)
  162:1  error Access of global variable 'sap' (sap.registerComponentDependencyPaths)
  171:3  error Access of global variable 'sap' (sap.ui.getCore)
  171:10 error Call to deprecated function 'getCore' (sap.ui.getCore)
  171:20 error Call to deprecated function 'attachInit' of class 'Core'
  172:18 error Access of global variable 'sap' (sap.ui.getCore)
  172:25 error Call to deprecated function 'getCore' (sap.ui.getCore)
  172:35 error Call to deprecated function 'getConfiguration' of class 'Core'
  172:54 error Call to deprecated function 'getLanguage' of class 'Configuration'
  184:5  error Access of global variable 'sap' (sap.ui.getCore)
  184:12 error Call to deprecated function 'getCore' (sap.ui.getCore)
  184:22 error Call to deprecated function 'attachInit' of class 'Core'
  190:7  error Access of global variable 'sap' (sap.ushell.Container.createRenderer)
  198:5  error Access of global variable 'sap' (sap.ui.getCore)
  198:12 error Call to deprecated function 'getCore' (sap.ui.getCore)
  198:22 error Call to deprecated function 'attachInit' of class 'Core'
  200:20 error Access of global variable 'sap' (sap.ui.getCore)
  200:27 error Call to deprecated function 'getCore' (sap.ui.getCore)
  200:37 error Call to deprecated function 'getConfiguration' of class 'Core'
  200:56 error Call to deprecated function 'getLanguage' of class 'Configuration'
  211:4  error Access of global variable 'sap' (sap.ui.getCore)
  211:11 error Call to deprecated function 'getCore' (sap.ui.getCore)
  211:21 error Call to deprecated function 'attachInit' of class 'Core'
  214:5  error Access of global variable 'sap' (sap.ushell.Container.createRenderer)

```

Is fixing those part of this issue as well or should I open a separate one?

**Comment by Thodd** [comment]
Hi,

the `sap.ushell.Container.createRednerer()` call is also deprecated and leads to synchronous creation of the Renderer UIComponent:
https://github.com/SAP/open-ux-tools/blob/main/packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js#L214

Setting the `async` parameter to `true` is probably not wrong, but I can't really comment on a modern alternative provided by the ushell. As said the `createRenderer` function itself is deprecated :(

Best regards,
Thorsten

**Comment by heimwege** [comment]
Cross link to https://github.com/SAP/open-ux-tools/issues/1679 as the replacement of `createRenderer` also needs to be done in the preview middleware.

**Comment by heimwege** [comment]
The locate-reuse-libs.js refactoring part might be no longer needed as the file will be deleted by https://github.com/SAP/open-ux-tools/issues/2172

**Comment by devinea** [comment]
Linter issues fixed for newer ui5 versions GTE 1.120.0 in https://github.com/SAP/open-ux-tools/pull/2334 
Hopefully soon with https://github.com/SAP/open-ux-tools/issues/2172 it will no longer be needed.
