### ISSUE TITLE
TBI - Support creation of sub sections in fpm-writer

### ISSUE THREAD

**Issue by 815are** [SAP/open-ux-tools#992]
As a developer I want to be able to use custom templates for custom (sub-)section creation with Page editor in OData V4 application object pages to be speed up my development.

### Description (include screenshots)
In addition to the existing custom section support on root-level, also custom (sub-)sections shall be supported on Object Pages (part of a group section).

Doc: https://ui5.sap.com/test-resources/sap/fe/core/fpmExplorer/index.html#/customElements/customSubSectionContent

Changes to be done:
1. Entry created in manifest like:
```
"targets": {
	"sample": {
		"type": "Component",
		"id": "Default",
		"name": "sap.fe.templates.ObjectPage",
		"viewLevel": 1,
		"options": {
			"settings": {
				"entitySet": "RootEntity",
				"content": {
					"body": {
						"sections": {
							"ReferenceFacet1": {
								"subSections": {
									"customSubSection1": {
										"type": "XMLFragment",
										"template": "sap.fe.core.fpmExplorer.customSubSectionContent.CustomSubSection1",
										"title": "Custom Subsection 1"
									}
								}
							},
```
2. Creation or referencing to existing fragment file(+handler.js as optional if requested), similar like for sections:
`event handler` js/ts file - https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/common/types.ts#L168
and js/ts file templates - [EventHandler.js](https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/templates/common/EventHandler.js) [EventHandler.ts](https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/templates/common/EventHandler.ts) 
fragment template - [Fragment.xml](https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/templates/common/Fragment.xml)

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Update manifest.json with new sub section entry
- [ ] Create or allow to reuse template fragment file with or without eventHandler
- [ ] Unit and integration tests

@tobiasqueck @schreckstefan @Klaus-Keller
